### ISSUE TITLE
haproxy support - local_ip

### ISSUE THREAD

**Issue by waszi** [baudehlo/Haraka#1004]
Could you add support for local_ip change via haproxy protocol. It is important when we are using plugins like connect.geoip (distance calculation) and haproxy as load balancer.

```javascript
diff -u connection.js.old connection.js 
--- connection.js.old	2015-06-03 14:48:44.495175225 +0200
+++ connection.js	2015-06-03 14:29:04.306419572 +0200
@@ -1091,6 +1091,7 @@
         ' dst_ip=' + dst_ip + ':' + dst_port);
     this.reset_transaction(function () {
         self.relaying = false;
+        self.local_ip = dst_ip;
         self.remote_ip = src_ip;
         self.remote_host = undefined;
         self.hello_host = undefined;
```

**Comment by smfreegard** [comment]
Sure - no problem.

`local_ip` and `local_port` were added after I added HAProxy support which is why this wasn't handled.  
See #1005 - I added the local and remote ports too as that seemed sensible.   Is that OK with you?
