### ISSUE TITLE
Embedding Haraka in other Node Module

### ISSUE THREAD

**Issue by martin1yness** [baudehlo/Haraka#1031]
Currently the way Haraka installs into NPM makes it challenging if not impossible to use as a module inside of another application. One can image developing an application ontop of Haraka and wanting to depend on it using the traditional NPM system.

```javascript
var haraka = require('Haraka);
// Override configuration source
haraka.config = function(name, type, cb, options) { 
  ..
};
// Add additional plugins
haraka.plugins.push(require('./myplugin'));

// start the service
haraka.startServer();
```

I'd like to help with the work, but i'm a bit fresh and don't know absolute best way to accomplish something like this in Node.

**Comment by baudehlo** [comment]
Honestly this is going to be pretty much impossible. Haraka is designed as
an application, not a library. If you want an SMTP server library, there
are others on NPM.

**Comment by martin1yness** [comment]
Other SMTP server libraries don't have the plugin support built in like Haraka. If it is not going to be feasible to embed I'll have to find a different way to integrate.
