### ISSUE TITLE
unable to send emails

### ISSUE THREAD

**Issue by rahul-desai3** [baudehlo/Haraka#1063]
I followed the steps mentioned here: https://haraka.github.io/manual/Outbound.html, except the Outbound Mail Hooks section. I dont have the MX records for the actual site yet. (I was trying to send email to other email address listed in the host list).

I used the code at the bottom of that page and placed it in plugins folder and ran it using Node. It is not able to find the `outbound` module even if I set the path to config folder (since we have `outbound.ini` in that directory).

How do I fix this?

**Comment by smfreegard** [comment]
It doesn't work like that.   It has to run inside a plugin in a running Haraka instance.   It's not a replacement for something like nodemailer which is what you sound like you're trying to use it for.

**Comment by rahul-desai3** [comment]
@smfreegard 
I now have it as a plugin in Haraka - I am using [this code](https://gist.github.com/rahul-desai3/238422d2e4426e1e580a) as `send_emails.js` file in `plugins` directory, also added the entry `send_emails` in `config/plugins` file.

Now when I run the Haraka instance using `sudo haraka -c .`, I get the following error:

```
[CRIT] [-] [core] TypeError: undefined is not a function
[CRIT] [-] [core]     at outnext (/private/etc/haraka_demo/plugins/send_emails.js:22:28)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:476:13
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/lib/async.js:142:25
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:499:17
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:95:15)
[NOTICE] [-] [core] Shutting down
```

What am I missing/doing wrong here?

**Comment by baudehlo** [comment]
A plugin has to implement a hook - you've just put all the code outside of
any hook.

I also think you're fundamentally failing to understand that Haraka is a
mail server, not a library for sending emails. The code in our docs for
sending a mail can only be triggered by an event (such as an incoming mail).

**Comment by rahul-desai3** [comment]
@baudehlo 
Ok, I changed my code. This is what it looks like now: [gist](https://gist.github.com/rahul-desai3/c75886bb84eeb5d84c1c). 

I do not get any error now if I run the Haraka instance.

How do I call this plugin to send emails? I eventually want to use this to send emails using a HTML form.

**Comment by smfreegard** [comment]
> How do I call this plugin to send emails? I eventually want to use this to send emails using a HTML form.

You don't want Haraka then.   Go and look at https://github.com/andris9/Nodemailer instead

**Comment by rahul-desai3** [comment]
I know this is not completely relevant to Haraka, but I am using Haraka as a service while using NodeMailer to send emails.

Here is my NodeMailer code (that uses Haraka): [gist](https://gist.github.com/rahul-desai3/318ff2dfd31f463536bd)

When I run this script, I get:
```
{ [Error: Can't send mail - all recipients were rejected]
  code: 'EENVELOPE',
  response: '550 I cannot deliver mail for <rahuldesai209@gmail.com>',
  responseCode: 550 }
```

In Haraka logs, I get:

```
[NOTICE] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] message mid="<1436471581989-fe524fc5-38d9b8da-00229e69@vmail.com>" size=444 rcpts=1/0/0 delay=0.005 code=CONT msg=""
[DEBUG] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] running queue hooks
[DEBUG] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] running queue hook in receive-and-save-emails plugin
[INFO] [-] [receive-and-save-emails] New inbound email detected, inserting into mongodb
[INFO] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] hook=queue plugin=receive-and-save-emails function=hook_queue params="" retval=OK msg=""
[DEBUG] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] running queue_ok hooks
[NOTICE] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] queue_ok code=CONT msg="Message Queued (3CFC82EC-8512-41D9-B51E-D563994352E6.1)"
[DEBUG] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] running reset_transaction hooks
[DEBUG] [-] [receive-and-save-emails] Email count = 10
[INFO] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] client [127.0.0.1] half closed connection
[DEBUG] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] running disconnect hooks
[NOTICE] [3CFC82EC-8512-41D9-B51E-D563994352E6.1] [core] disconnect ip=127.0.0.1 rdns="Unknown" helo="Rahuls-MacBook-Air.local" relay=N early=N esmtp=Y tls=N pipe=N txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=444 lr="" time=0.253
```

Any idea how to fix this?

**Comment by smfreegard** [comment]
You need to allow 127.0.0.1 to relay (it isn't allowed to by default unlike other SMTP servers) either use the relay plugin or configure SMTP AUTH via the auth/flat_file plugin (and set-up Nodemailer to use SMTP AUTH).   The relay plugin is the simpler although marginally less secure approach.

The logs you posted don't appear to relate to anything related to the nodemailer error BTW.

**Comment by rahul-desai3** [comment]
@smfreegard I went through the documentation of [relay plugin](https://haraka.github.io/manual/plugins/relay.html). It says that authentication is one way of enabling it, but it will send emails through *that* SMTP server. 

I want my Haraka server to work independently.  Is there any other way to enable relaying so that the email is sent directly through my local Haraka server and not using any third party SMTP like Google, etc. ?

**Comment by smfreegard** [comment]
Use this: https://gist.github.com/smfreegard/ff79d02aeb94b9065359 instead of queue/smtp_forward and it Haraka will always queue and route to MX.

**Comment by rahul-desai3** [comment]
@smfreegard I dint quite get you. I am not using `queue/smtp_forward` and I dont know if it is an internal thing for Haraka which it might be using. Can you please elaborate on your solution? Where exactly should I add that code you gave? should I create a new plugin with your code?

I am still new to Haraka and learning.
