### ISSUE TITLE
Release 2.7.0

### ISSUE THREAD

**Issue by baudehlo** [baudehlo/Haraka#1065]
Ticket for discussion on releasing 2.7.0.

Discuss any open issues we need to get fixed before release here.

I think (gut feel) we are very close to being able to cut a release. Thoughts?

**Comment by msimerson** [comment]
I have a very significant update to karma that's mostly done. I've changed the config file format of the rules (all new methods, old config settings still work) such that rules are simpler, can be read, written, scored, and then [reported on](https://mail.theartfarm.com/haraka/logs/6E9A2F70-2CD7-42DE-A09D-323A292DC3D2) posthumously.

**Comment by msimerson** [comment]
Oh, and it uses the new redis pub/sub support in Results, so at some future date when I choose to longer support the old config settings, karma can stop "hooking the world"

**Comment by smfreegard** [comment]
Sounds fine to me; I don't have anything pressing to go in.

**Comment by baudehlo** [comment]
ETA on karma changes?

**Comment by msimerson** [comment]
Code is all done, config file is updated, I just need to finish updating the docs. Highly likely this weekend.

**Comment by msimerson** [comment]
The karma changes are in, a few other bug fixes have merged in as well since then. I think we should release, and then look forward to 2.7.1.

**Comment by smfreegard** [comment]
#1081 must be merged prior to release.   If not - then a lot of potential breakage will occur as the plugin ordering in `config/plugins` is not honoured.

#1075 should also be merged; I've commented on the change from milliseconds to seconds.

I'd also like to see #952 go in.  The tests are broken, not the PR.

The rest are all pretty much dead in the water.

**Comment by msimerson** [comment]
Ah yes, I'll try to get them tested and merged in the next few days.

**Comment by dontforget** [comment]
Hello guys!

When we can expece v2.7 release date?

Thanks.

**Comment by baudehlo** [comment]
We will probably push out RC1 on Monday.

**Comment by soundslocke** [comment]
Exciting!

**Comment by Dexus** [comment]
Please merge #1118 before release v2.7

It has many improvments, fixes and makes compatible to each iojs (that V8 build with g++ >= 4.8).
