### ISSUE TITLE
question about process attachment ?

### ISSUE THREAD

**Issue by ngotau** [baudehlo/Haraka#1077]
Thank you for your great work of Haraka. 
I would like to write a plugin that zip all attachments file then put zipped file back to email.
Follow attachment plugin I save attachments file to disk, zip it successful, but don't know how to
put zipped file back to email.
Please advise.

**Comment by smfreegard** [comment]
Unfortunately at this time; modifying the message e.g. removing/adding attachments and message parts is very hard to do in Haraka and as such we don't offer a way to do this currently.   You'd probably have to discard the original message and build a completely new message from the old one.

**Comment by ngotau** [comment]
Thank you for your reply.
I'll try to build new one.
