### ISSUE TITLE
AUTHENTICATION REQUIRED

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1080]
hello i am new in  nodejs and need help much. 
i want to build a Haraka outbound server on cent OS 6.5
I have configured Haraka outbound server but unfortunately an error  occurred
 listed as below:
when i tries to send test mail it shows authentication error i have attached the error in form of screen shot listed below.
![screenshot from 2015-07-17 15 29 01](https://cloud.githubusercontent.com/assets/13378593/8744987/0dbd272a-2c99-11e5-892d-5aef11ce2300.png)

**Comment by smfreegard** [comment]
You're using port 587 which requires SMTP Auth.   So you need to set-up TLS and enable an auth/* plugin e.g. auth/flat_file etc.

**Comment by hemsinfotech** [comment]
how we can disable tls also our script support only non tls smtp auth.

**Comment by vivek779** [comment]
i have configured TLS and now it is generating another error plz help me solve this issue also
![screenshot from 2015-07-17 16 13 55](https://cloud.githubusercontent.com/assets/13378593/8745580/f17a7616-2c9e-11e5-8fce-b486cae3988e.png)

**Comment by smfreegard** [comment]
You might have configured TLS - but you aren't using it, so AUTH isn't offered.   Haraka was designed to be more secure by default, so the AUTH extension isn't offered unless the connection is encrypted (because AUTH PLAIN and LOGIN send the password effectively in the clear).

If you want to remove that; you'd have to edit auth/auth_base.js and remove this line:
https://github.com/baudehlo/Haraka/blob/master/plugins/auth/auth_base.js#L16

**Comment by vivek779** [comment]
hello there i am still not able to solve my issue i have tried to remove that line 16 in /plugins/auth/auth_base.js  to disable tls .Bt the error is same 
please  help me solve the issue i have done everything i could guide me.
 Attaching the error as well edited auth _base.js file of my system
![screenshot from 2015-07-21 11 19 46](https://cloud.githubusercontent.com/assets/13378593/8793926/fc2243f6-2f9a-11e5-9b20-a1e39b4a0f7e.png)
![screenshot from 2015-07-21 11 23 26](https://cloud.githubusercontent.com/assets/13378593/8793928/05686ed6-2f9b-11e5-9e31-b34771383ab1.png)

**Comment by smfreegard** [comment]
That's because it looks like you've removed the entire function and not just the line I specified.   Simply comment the line I told you to and it should work.

**Comment by vivek779** [comment]
yes i tried with the single line bt the result is same 
attaching screen shoot 
![screenshot from 2015-07-21 15 19 35](https://cloud.githubusercontent.com/assets/13378593/8797897/35f0127c-2fbc-11e5-8ae6-a6fb97146d92.png)
![screenshot from 2015-07-21 15 25 15](https://cloud.githubusercontent.com/assets/13378593/8798012/f1805db2-2fbc-11e5-90f3-832e41001444.png)

**Comment by smfreegard** [comment]
Ok - remove this if {} block: https://github.com/baudehlo/Haraka/blob/master/plugins/auth/flat_file.js#L20 and it should work after that.

**Comment by vivek779** [comment]
i tried to remove that block bt after running haraka outbound service its show error
Attaching screen shot
![screenshot from 2015-07-21 15 41 33](https://cloud.githubusercontent.com/assets/13378593/8798353/408d77f8-2fbf-11e5-803c-4dc50db72976.png)
![screenshot from 2015-07-21 15 42 22](https://cloud.githubusercontent.com/assets/13378593/8798354/408f4c0e-2fbf-11e5-8708-ab1b92aff633.png)

**Comment by smfreegard** [comment]
You've removed the opening curly brace e.g { at the end of the:

`exports.hook_capabilities = function (next, connection) {`

line

**Comment by vivek779** [comment]
thank u soo much for helping me
server is running now .

**Comment by smfreegard** [comment]
You're welcome - glad you got it working.

You will need to move the file to wherever you installed Haraka (e.g. haraka -i /path/to/install) into the plugins directory to prevent your changes from being overwritten on an upgrade (you only need to copy auth_flat_file.js).

**Comment by vivek779** [comment]
ok i will  can you please tell one more thing i am using 
operating system =centos-6.5 64 Bit OS
Memory =1 GB
V swap = 1024 MB
Disk Space = 80 GB
Bandwidth = 1.5 TB
and speed of sending mail is 5 mail per second is there any way to increase that speed

**Comment by smfreegard** [comment]
Disable as many plugins as you can.  If you're only doing authenticated relay, then you can probably disable all of them except for auth/flat_file.

Otherwise, make sure `nodes=cpus` in `config/smtp.ini`

That should be about as fast as it can then go on that hardware.

**Comment by vivek779** [comment]
ok and can you just help with one more query .I installed haraka-outbound on vps and send mails whenever i close the putty session the mail sending application shows connection refused. 
Is there any way to keep running the server background even if I closed the session.
