### ISSUE TITLE
haraka

### ISSUE THREAD

**Issue by nrshems** [baudehlo/Haraka#1084]
hello sir,

Please send the doc of haraka installation properly

Thank You

**Comment by smfreegard** [comment]
It tells you here: https://github.com/baudehlo/Haraka/blob/master/README.md how to install it.

You will have to work out how to install Node.js on your operating system of choice first - there are plenty of docs online that tell you how to do that.

**Comment by nrshems** [comment]
please suggest me..which o.s will be best

**Comment by smfreegard** [comment]
Whatever OS you are most comfortable with that can run Node.js.   There is no right answer.

**Comment by nrshems** [comment]
sir please what the firt step to install the haraka
And link i have use already

**Comment by nrshems** [comment]
i have use centos6

**Comment by smfreegard** [comment]
Install node.js - you can find an RPM for CentOS on their website I think.   Install it, then run:

`npm install -g Haraka`

Then follow the instructions in the README.

**Comment by nrshems** [comment]
sir, i will install on my base machine or vps

**Comment by Abdeljalil0Cyclo** [comment]
Hello , there is issue installing Haraka on centos 6.10 server , after installing nodejs ,  Haraka installation fails using npm

**Comment by KingNoosh** [comment]
How does it fail? Can you provide any logs?

**Comment by Abdeljalil0Cyclo** [comment]
i have posted the logs above

**Comment by Abdeljalil0Cyclo** [comment]
I solved it  on CentOS 6.10 , it only worked for me with gcc / g++ version 6.3.0 , like this :


yum install centos-release-scl-rh
yum install devtoolset-6-gcc

gcc and g++ --version should output 6.3.0

and

sudo npm i -g --unsafe-perm --allow-rout Haraka

this how i installed it on debian 9 also
