### ISSUE TITLE
Speed of sending mail in Haraka-outbound server

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1085]
i am using 
operating system =centos-6.5 64 Bit OS
Memory =1 GB
V swap = 1024 MB
Disk Space = 80 GB
Bandwidth = 1.5 TB
and speed of sending mail is 5 mail per second is there any way to increase that speed

**Comment by DarkSorrow** [comment]
Do you send with one client connected? I suppose you can try to send with several client at the same time, its probably more a limitation with the client you use than haraka itself i think.

**Comment by vivek779** [comment]
ok and can you just help with one more query i installed haraka-outbound   on vps and send mails  whenever i close the putty session  the mail sending application shows connection refused is there any way to keep running the server background even if i closed the session

**Comment by vivek779** [comment]
I am also trying to search how to set  mail sending limits on  new users on the servers bt not able to find could you please guide me on this alsoo

**Comment by smfreegard** [comment]
https://github.com/baudehlo/Haraka/blob/master/contrib/haraka.init is a CentOS/RHEL initscript for Haraka.   You will need to modify the paths accordingly and install it in /etc/init.d/haraka, then use chkconfig to enable it at boot.

As for rate limiting new users; there is a rate_limit plugin; but it wouldn't have any concept of 'new' users, so you'll either have to modify it accordingly or use scripts to build it's config as per your requirements.

**Comment by vivek779** [comment]
I tried to install as per you said bt it is giving me errors could you help me to solve this also
i am working on Cent OS 
![screenshot from 2015-07-22 17 22 40](https://cloud.githubusercontent.com/assets/13378593/8824802/efee9f06-3096-11e5-80af-91a607e15c39.png)

**Comment by smfreegard** [comment]
Sorry - no idea on that.

**Comment by vivek779** [comment]
ok i removed the error bt  when i tries to start the service it shows stopped could you please guide what mistake i am doing  attaching screenshot
![screenshot from 2015-07-23 17 49 47](https://cloud.githubusercontent.com/assets/13378593/8850170/514370b6-3163-11e5-8d46-a707dc9cbbae.png)
![screenshot from 2015-07-23 17 50 55](https://cloud.githubusercontent.com/assets/13378593/8850181/6d239acc-3163-11e5-9508-cb703d65d3a4.png)
