### ISSUE TITLE
Is there are plugin for create smtp user instance from frontend 

### ISSUE THREAD

**Issue by hemsinfotech** [baudehlo/Haraka#1087]
Is there are plugin for create smtp user instance from frontend (web interface) and can assign partiular limit of sending emails of per day or per month.

**Comment by msimerson** [comment]
No. You'd need to develop your web interface, as well as some provisioning logic to deploy a Haraka instance with those particular settings applied. You'll want to look into the rate_limit plugin for throttling and I'd be looking hard at Docker or FreeBSD jails to thinly provision your instances.

**Comment by hemsinfotech** [comment]
is there any suggestion can you give to me for how to setup the web interface to create smtp instance from frontend

**Comment by msimerson** [comment]
If I were doing it, I'll install node.js and then follow [the bouncy ball](http://expressjs.com/starter/installing.html) to create an Express.js web app. Then drop in a bower.json (attached) and use it with bower to automatically fetch the latest versions of the web development frameworks listed.

````json
{
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "client/bower_components",
    "test"
  ],
  "dependencies": {
    "html5-boilerplate": "*",
    "modernizr": "*",
    "bootstrap": "*",
    "jquery": "~2.1.1",
  }
}
````

You can automate the download and extraction of these development frameworks with grunt and a Gruntfile.js, such as this one:

````js
module.exports = function(grunt) {
    grunt.loadNpmTasks('grunt-browserify');
    grunt.loadNpmTasks('grunt-concurrent');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-bower');
    grunt.loadNpmTasks('grunt-bower-install-simple');

    // Project configuration.
    grunt.initConfig({
        'bower-install-simple': {
            options: {
                color: true,
                directory: 'bower_components'
            },
            'prod': {
                options: {
                    production: true
                }
            },
            'dev': {
                options: {
                    production: false
                }
            }
        },
        bower: {
            dev: {
                dest: 'html/vendor',
                js_dest: 'html/js/vendor',
                css_dest: 'html/css/vendor',
                fonts_dest: 'html/fonts/vendor',
                options: {
                    expand: false,
                    keepExpandedHierarchy: false
                },
            }
        },
        clean: {
            build: ['build'],
            dist: ['node_modules', 'bower_components']
        },
    });

    // Default task(s).
    grunt.registerTask('default', ['bower-install-simple', 'bower']);
};
````

**Comment by hemsinfotech** [comment]
thanks really working help for me. is there any basic code for create smtp instance with username and password. and hostname , port should be default. and these all instance listen on default port and have some limitation of sending after reach on limit the defined error should shows the user.
