### ISSUE TITLE
outbound email inserting '\n ' at various places

### ISSUE THREAD

**Issue by proj59598** [baudehlo/Haraka#1089]
I am using node mailer to send an html mail to  Haraka, but the delivered mail is inserting newline followed by space after every certain number of characters. Haraka is set up as an outbound mail server. Opening the delivered mail on mobile gmail e.g. I see "%0a%20" in an <a href>.

**Comment by smfreegard** [comment]
Probably 998 characters; as Haraka will break massive lines.   But you're going to need to provide way more information on this (e.g. a full example) to be able to see if there is a bug or not.

**Comment by proj59598** [comment]
Here it is , i use node mailer to send a huge html as a string to haraka outbound server.

nodemailer = require('nodemailer')
smtpTransport = require('nodemailer-smtp-transport')

var transport = nodemailer.createTransport(smtpTransport(smtp));
transport.sendMail({
  from:'haraka outbound mail server'
  to:'a gmail address'
 subject:'subject'
 html:'an html page as a long javascript string'
})

Is there any way around the 998 character limit in haraka ?

**Comment by smfreegard** [comment]
It's not a limit in Haraka - it's an SMTP limit.  See https://tools.ietf.org/html/rfc5322#section-2.1.1

If you exceed 998 characters on one line and send the mail somewhere else; then it may or may not work.  Ideally you should fix whatever you are using to generate the page to split the lines so they aren't massive.

You can change the limit by:   `echo 2048 > config/max_data_line_length`

But be warned; your mail is likely to still get messed up if you do.

**Comment by baudehlo** [comment]
If you're using Jade for generating the HTML, pass in {pretty: true} to
render and you'll get carriage returns in it.

**Comment by proj59598** [comment]
Thanks a lot! 
I was able to resolve this issue by not stripping new line from my generated html.
