### ISSUE TITLE
how to run haraka as background server or as a boot 

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1096]
hi i am new in node.js  field  .I have just recently installed haraka -outbound server on vps bt whenever i closed the putty session it stops i want it to be run in background even if i closed the putty session  i  have used init script to run is as boot i created haraka init script at /etc/init.d/ and started with chkconfig bt when i start the service  it wont start  i have installed haraka at usr/local/lib/node_modules/Haraka and have run haraka outbound server from /root/haraka .
please guide me to solve this  
attaching screenshot
![screenshot from 2015-07-23 17 50 55](https://cloud.githubusercontent.com/assets/13378593/8869106/ba8c571e-31fd-11e5-9183-76081c31310f.png)
![screenshot from 2015-07-24 12 24 44](https://cloud.githubusercontent.com/assets/13378593/8869237/0d0681bc-31ff-11e5-85e7-6fe3487506a2.png)

**Comment by msimerson** [comment]
There are boot scripts in the contrib directory for several OS.  Try them.

**Comment by vivek779** [comment]
i have already boot script from your contrib directory i have mentioned above as well the errors i am facing could you please help me solve this

**Comment by smfreegard** [comment]
Check all the paths in the file - I can see at leasr one reference of /etc/haraka which you haven't changed specifically for your environment.

**Comment by vivek779** [comment]
yes I noticed that and I have changed the reference from /etc/haraka to :
/root/haraka   becoz my  haraka_outbound files are present there still it wont start 
my configuration files of haraka are at /root/haraka  
I have tried different combinations also bt it wont start
Ataching screenshot 
![screenshot from 2015-07-27 14 54 46](https://cloud.githubusercontent.com/assets/13378593/8902563/7a9e1f9c-346f-11e5-879a-20f4071e21b5.png)
![screenshot from 2015-07-27 14 54 13](https://cloud.githubusercontent.com/assets/13378593/8902567/7d5c500a-346f-11e5-8a4c-f414210ee4db.png)

**Comment by smfreegard** [comment]
I'm guessing you don't have a lot of Linux/UNIX experience.

Your exec= line is wildly wrong.   /usr/local/lib/node_modules/haraka doesn't even exist.   Additionally /root/haraka is an astonishingly poor place to install the Haraka directory to.

`which haraka` will show you where the Haraka 'binary' is installed (likely to be /usr/local/bin/haraka or /usr/bin/haraka depending on your OS) and that is what exec= should be pointed to.

You will also need to set `daemonize=true` in config/smtp.ini for it to work correctly.

**Comment by vivek779** [comment]
It exits on my OS and haraka installed automatically to that path when I started the installation the path exits on OS  see on screen shot  and all the files are present there itself only 
![screenshot from 2015-07-27 15 39 07](https://cloud.githubusercontent.com/assets/13378593/8903443/b6f84eee-3475-11e5-9d34-2750649a5524.png)

and I have  set daemonize =true in smtp.ini bt now my haraka  server stops automatically
now you suggest what should I do 
I know installing haraka directory at /root/haraka is poor place  and yes I have  experience bt not to that level on what you are so please guide me

**Comment by smfreegard** [comment]
It *doesn't* exist.  exec= should point to the binary; you're attempting to point it at a directory (that doesn't exist).  /usr/lib/node_modules/haraka and /usr/lib/node_modules/Haraka are different.  Names are case-sensitive in UNIX.

And daemonize is working as it should - it double-forks and exits from the controlling terminal.  If you check port 25 it will still be running.

Now - if you actually listen to what I'm telling you to do - you might actually get this working.   Run the command: `which haraka` and then put that into the exec= line in the initscript.   It should work correctly then....

**Comment by vivek779** [comment]
it run perfectly now
thanks a lot I always  listens your advice thats why I asked too much from you you always helped me and guided me thank u
