### ISSUE TITLE
User limit 

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1102]
hi 
I just installed haraka outbound and tries to set user limit   I used rate_limit plugins and since it require redis server so I commented the redis server section in  rate_limit.js file  and run the service  bt when I tries to send mail it shows  
[CRIT] [C1D6142D-9594-49E7-BB86-5A0E9180DEC3] [core] Plugin rate_limit timed out on hook disconnect - make sure it calls the callback
plz guide me on this  attaching screenshot of files and errors
![screenshot from 2015-07-28 17 00 32](https://cloud.githubusercontent.com/assets/13378593/8930303/62e07a5e-354a-11e5-8191-286179b51630.png)
![screenshot from 2015-07-28 17 01 19](https://cloud.githubusercontent.com/assets/13378593/8930304/62e5381e-354a-11e5-8ff4-f282a42c873a.png)

**Comment by vivek779** [comment]
Actually I tried with redis server also bt it shows error thats why I  commented in rate_limit.js file 
and guide me also how to set rate_limit.ini file to set user msg limit on haraka-outbound server

**Comment by baudehlo** [comment]
You need a working installation of redis. You can't just comment out code
willy-nilly and expect it to still work.

**Comment by vivek779** [comment]
ok I figure it out how to run rate_limit plugin with redis server and it runs 
but whenever I tries to send mail to it it shows error
plugin_rate limit time out 
plz guide me what mistake i am doing  attaching screenshot
![screenshot from 2015-07-10 16 05 13](https://cloud.githubusercontent.com/assets/13378593/8950981/33287298-35e6-11e5-8e13-4da3da3595dc.png)
![screenshot from 2015-07-29 11 33 21](https://cloud.githubusercontent.com/assets/13378593/8950982/33286eb0-35e6-11e5-98d7-5408304f74b4.png)
