### ISSUE TITLE
Failed to setup listeners: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1103]
hi 
After running haraka service in /etc/haraka it gives the following error when i tries to send mail 
![screenshot from 2015-07-29 17 25 06](https://cloud.githubusercontent.com/assets/13378593/8956789/d21fe504-3616-11e5-962a-e6cd6cb5a69c.png)

 can anybody just guide me how to solve this error I tries everything bt not able to solve it
attachin  the screenshot

**Comment by smfreegard** [comment]
What do you have in your `listen=` option in `config/smtp.ini`?

Note: please don't post another screenshot.  Learn how to quote in Github and paste the output.

**Comment by vivek779** [comment]
listen=[:0]:587

**Comment by vivek779** [comment]
looks like i figured it out it is syntax mistake i am doing it should have 
listen=[::0]:587
