### ISSUE TITLE
Plugin rate_limit timed out on hook disconnect 

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1104]
I want to set user limit on particular user as how much mails he can send
when I add rate_limit plugins it gives the following error:

[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[DEBUG] [-] [core] no timeout in auth/flat_file.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin auth/flat_file timeout is: 30s
[INFO] [-] [core] loaded 7185 Public Suffixes
[INFO] [-] [core] loaded TLD files: 1=882 2=5813 3=2287
[DEBUG] [-] [core] no timeout in auth/auth_base.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin auth/auth_base timeout is: 30s
[DEBUG] [-] [core] registered hook capabilities to auth/flat_file.hook_capabilities
[DEBUG] [-] [core] registered hook unrecognized_command to auth/flat_file.hook_unrecognized_command
[INFO] [-] [core] Loading plugin: spf
[DEBUG] [-] [core] no timeout in spf.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin spf timeout is: 30s
[DEBUG] [-] [core] registered hook ehlo to spf.hook_ehlo
[DEBUG] [-] [core] registered hook helo to spf.hook_helo
[DEBUG] [-] [core] registered hook mail to spf.hook_mail
[INFO] [-] [core] Loading plugin: dkim_sign
[DEBUG] [-] [core] no timeout in dkim_sign.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin dkim_sign timeout is: 30s
[DEBUG] [-] [core] Returning boolean true for main.disabled=true
[DEBUG] [-] [core] registered hook queue_outbound to dkim_sign.hook_queue_outbound
[INFO] [-] [core] Loading plugin: rate_limit
[DEBUG] [-] [core] no timeout in rate_limit.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin rate_limit timeout is: 30s
[DEBUG] [-] [core] registered hook connect to rate_limit.incr_concurrency
[DEBUG] [-] [core] registered hook disconnect to rate_limit.decr_concurrency
[DEBUG] [-] [core] registered hook connect to rate_limit.hook_connect
[DEBUG] [-] [core] registered hook rcpt to rate_limit.hook_rcpt
[NOTICE] [-] [core] Listening on :::587
[DEBUG] [-] [server] running init_master hooks
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue
[INFO] [-] [core] [outbound] Loading the queue...
[NOTICE] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] connect ip=104.131.90.132 port=37797 local_ip=:: local_port=587
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running lookup_rdns hooks
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running connect hooks
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running connect hook in rate_limit plugin
[INFO] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] client [104.131.90.132] half closed connection
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running disconnect hooks
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running disconnect hook in rate_limit plugin
[CRIT] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] Plugin rate_limit timed out on hook connect - make sure it calls the callback
[CRIT] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] Plugin rate_limit timed out on hook disconnect - make sure it calls the callback
[INFO] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] hook=disconnect plugin=rate_limit function=decr_concurrency params="" retval=DENYSOFT msg="plugin timeout"
[DEBUG] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] running deny hooks
[NOTICE] [5DCD29C3-319D-4125-AEA4-AB8B73D93D89] [core] disconnect ip=104.131.90.132 rdns="DNSERROR" helo="" relay=N early=N esmtp=N tls=N pipe=N txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=45.018

guide me as how i do to set rate_limit plugin i tried bt not got the results

**Comment by Dexus** [comment]
Your Server can't resolve DNS... so you run into a timeout.
Use a working DNS server that can resolve the Hosts, and it will run for you.

@smfreegard can be closed.

**Comment by Dexus** [comment]
Hi, first of all I want to apologize. I had overlooked something: The timeout is triggered both connect and disconnect.

Please update your config for rate_limit. default must uncommented: https://github.com/baudehlo/Haraka/blob/master/config/rate_limit.ini

**Comment by vivek779** [comment]
hi there i wanted to set user limit on how much mail  a particular users send so for that i am using rate_limit plugin pleas also guide me how to do this also
Attaching my  rate_limit.ini
; Example configuration file for the rate_limit plugin

 redis_server =92.48.88.171
 tarpit_delay = 10

[concurrency]
; NOTE: this limit is per server child and does not use Redis
; Limit an IP or host to a maximum number of connections

; Don't limit connections from localhost
127 = 0

; Freemail
; hotmail.com = 20
; yahoo.com = 20
; google.com = 20

; default = 5

[rate_conn]
; Maximum number of connections from an IP or host over an interval

127 = 0
; default = 5  ; no interval defaults to 60s

[rate_rcpt_host]
; Maximum number of recipients from an IP or host over an interval

127 = 0
; default = 50/5m  ; 50 RCPT To: maximum in 5 minutes

[rate_rcpt_sender]
; Maximum number of recipients from a sender over an interval

127 = 0
; default = 50/5m

[rate_rcpt]
; Limit the rate of message attempts over a interval to a recipient

127 = 0
; default = 50/5m

[rate_rcpt_null]
; Limit the number of DSN/MDN messages by recipient

; default = 1

**Comment by Dexus** [comment]
```
; Example configuration file for the rate_limit plugin

; redis_server = 1.2.3.4
; tarpit_delay = 30

[concurrency]
; NOTE: this limit is per server child and does not use Redis
; Limit an IP or host to a maximum number of connections

; Don't limit connections from localhost
127 = 0

; Freemail
; hotmail.com = 20
; yahoo.com = 20
; google.com = 20

default = 5

[rate_conn]
; Maximum number of connections from an IP or host over an interval

127 = 0

; no interval defaults to 60s
default = 5


[rate_rcpt_host]
; Maximum number of recipients from an IP or host over an interval

127 = 0

; 50 RCPT To: maximum in 5 minutes
default = 50/5m

[rate_rcpt_sender]
; Maximum number of recipients from a sender over an interval
; set for sender sender@example.com 10 messages in 5 minutes
sender@example.com = 10/5m
127 = 0
default = 50/5m

[rate_rcpt]
; Limit the rate of message attempts over a interval to a recipient

127 = 0
default = 50/5m

[rate_rcpt_null]
; Limit the number of DSN/MDN messages by recipient

default = 1
```
