### ISSUE TITLE
Seprate queue for diffrent users

### ISSUE THREAD

**Issue by vivek779** [baudehlo/Haraka#1105]
hi I am new in nodejs  just wanna know how to set or create seperate queue for seperate users 
. When multiple users send mail from haraka-outbound server mail got saved in the same queue and i cant figure out which user sending mails please guide me on this

**Comment by smfreegard** [comment]
There is no way to do that currently.   Patches welcome though :-)

**Comment by vivek779** [comment]
Okkss and if there any way that i puts users and password in database in mysql form and able to fetch them in auth_flat_file.ini . I am trying really hard bt not able to get the results it would be great if you help me
