### ISSUE TITLE
hook_bounce: param err.bounced_rcpt and err.deferred_rcpt undefined

### ISSUE THREAD

**Issue by hatsebutz** [baudehlo/Haraka#1106]
The bounce-hook does not get passed bounced_rcpt and deferred_rcpt.

I'm not sure (and not that familiar with nodejs), but I think there is a bug in 

HMailItem.prototype.try_deliver_host - finish_processing_mail:

hmail.temp_fail("Some recipients temp failed: " + fail_recips.join(', '), { **rcpt**: fail_recips, mx: mx });
[...]
hmail.bounce("Some recipients failed: " + bounce_recips.join(', '), { **rcpt**: bounce_recips, mx: mx });
[... and later in _bounce ..]
HMailItem.prototype._bounce = function (err, opts) {
    err = new Error(err);
    if (opts) {
        err.mx = opts.mx;
        err.deferred_rcpt = opts.**fail_recips**;
        err.bounced_rcpt = opts.**bounce_recips**;
    }
    this.bounce_error = err;
    plugins.run_hooks("bounce", this, err);
};

Could someone have a look if this is actually the error?

gerhard

**Comment by smfreegard** [comment]
> The bounce-hook does not get passed bounced_rcpt and deferred_rcpt.

The bounce hook shouldn't get deferred recipients as they *haven't* bounced.   Deferred recipients remain in the queue and a retried until the retry timers expire, then at that point they bounce.

Hook bounce is used like this:

`````
exports.hook_bounce = function (next, hmail, err) {
     // hmail.todo.rcpt_to === recipients that bounced
     // err.message === bounce reason
    return next();
}
`````

So I can't see a bug.

**Comment by hatsebutz** [comment]
Hi, finally found the commit in question:
https://github.com/baudehlo/Haraka/commit/3201299b2ae7c908a61932968a126e9c22b733e4

I think its just something like a typo and not intended, but may be I'm wrong: 
This commit added in outbound.js [lines 1011] (https://github.com/baudehlo/Haraka/commit/3201299b2ae7c908a61932968a126e9c22b733e4#diff-0610ac4c7da6258a441a4f36a6358653R1011) and [line 1018] (https://github.com/baudehlo/Haraka/commit/3201299b2ae7c908a61932968a126e9c22b733e4#diff-0610ac4c7da6258a441a4f36a6358653R1018) the `opts` parameter with
 `{ rcpt: fail_recips }` (resp. `{ rcpt: bounce_recips }`)
But at end of commit [line 1233] (https://github.com/baudehlo/Haraka/commit/3201299b2ae7c908a61932968a126e9c22b733e4#diff-0610ac4c7da6258a441a4f36a6358653R1233) the code reads 
`err.deferred_rcpt = opts.fail_recips`
and I can't see `opts.fail_recips` being set anywhere in the code. Even a full grep on the code does not show up any other code.

I'm actually looking to get the recipients and their bounce codes (SMTP code and extended code) in a bounce hook to be able to parametrize an outbound-rate-limit, but I can't get those codes.

Additionally, [outbound.js at master, line 1268] (https://github.com/baudehlo/Haraka/blob/master/outbound.js#L1268) reads:
`reason = code + ' ' + ((extc) ? extc + ' ' : '') + response.join(' ');`
but is only applied for SMTP error codes after RCPT or "dot_lmtp" and no other cases (like "dot" without LMTP).
Other cases are handled at [outbound.js at master, line 1268] (https://github.com/baudehlo/Haraka/blob/master/outbound.js#L1280) like that:
`reason = response.join(' ');`
For reasons I do not understand code and extended code are omitted in the reason-string passed.

Any hints would be welcome. Maybe I could prepare a pull request on a fork (didn't do that yet) if the change is likely to be accepted.
