### ISSUE TITLE
HELO/rDNS issue while using multiple outbound ip

### ISSUE THREAD

**Issue by MojaveKid** [baudehlo/Haraka#1114]
Hi guys,

Im using the multiple outbound ip plugin by baudehlo (#442). 

However, HELO/rDNS check (an anti-spam technique) fails because the HELO string used is different from the rDNS name.

Say you have a mail server mail.xyz.com at 111.111.111.111 and you have an interface  111.111.222.222 (foomail.xyz.com)

If I understand correctly, Haraka issues

HELO mail.xyz.com 

when connecting to a targeted mail server.

Suppose the email went out using interface 111.111.222.222

If the targeted mail server performs rDNS lookup, it will use 111.111.222.222 and resolves this to foomail.xyz.com

HELO and rDNS will not match:   mail.xyz.com != foomail.xyz.com

Is there a way where we can set the HELO connection string before the IP binding to the mx ?

Thanks.

**Comment by Dexus** [comment]
I will take a look what i can make, perhaps a new plugin/config needed for that...

**Comment by Dexus** [comment]
a new param is now available: `mx.bind_helo`
use at the sameway as mx.bind in #442

**Comment by Dexus** [comment]
@smfreegard can you close this now?

@MojaveKid for docs look into https://github.com/baudehlo/Haraka/blob/master/docs/Outbound.md
