### ISSUE TITLE
Attachment scan by VirusTotal

### ISSUE THREAD

**Issue by Dexus** [baudehlo/Haraka#1124]
I am planning a plugin that attachments should check with VirusTotal.

What do you think of the idea? 

Problem may be that there is a private API key is required , but then also more Request ( Public Api only 4 requests ) to settle.
@smfreegard can you lable as idea

**Comment by smfreegard** [comment]
You're thinking about using this:  https://api.vtapi.net/en/doc/virustotal-private-api-cookbook.html
I think it's a fine idea for a plugin.   We have commercial plugins like messagesniffer already.

You could also check out - http://www.team-cymru.org/MHR.html - I've used this before too.  It's probably not as good as VirusTotal though.

**Comment by Dexus** [comment]
Correct, this API I meant.

I also look to https://www.metascan-online.com and will look to create a plugin like https://github.com/mattgaff/Metascan-Email-Relay/

**Comment by Dexus** [comment]
Done with #1161
