### ISSUE TITLE
IPv6 compatibility: ToDoList

### ISSUE THREAD

**Issue by Dexus** [baudehlo/Haraka#1125]
To make Haraka full IPv6 compatible we need to add more checks that covers the IPv4 checks, to get the same result on IPv6 connects.

- [x] review all current IPv4 checks in helo.checks and add IPv6 compatible checks
- [x] data.uribl
- [x] all IPv4 RegExp Test, must also check against IPv6
- [x] check that also used IPv6 BLs
- [x] resolve must be made compatible for use with IPv6
- [x] update regexp with "IPv6:" Prefix in IPv6 helo check statements

---
If you have some additional tasks, please let it me know.
Thats my first small look, what need to be done.

https://www.ietf.org/rfc/rfc2821.txt

**Comment by msimerson** [comment]
I'd suggest moving all those checks into net_utils. We've already got some helper functions in there and having additional ones in there promotes reuse.

**Comment by Dexus** [comment]
:+1: the first steps are made.

**Comment by Dexus** [comment]
@baudehlo @msimerson @smfreegard 
Any known task that i don't have covered in my list?
