### ISSUE TITLE
552 Too many received headers - possible mail loop

### ISSUE THREAD

**Issue by 0vermind** [baudehlo/Haraka#1150]
>Delivery to the following recipient failed permanently:

     tergetname@domain.net

>Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain domain.net by serverip. [serverip].

>The error that the other server returned was:
552 Too many received headers - possible mail loop (187DB187-812C-4995-BC87-D9657C56AB3A.1) (E7E743CB-4B72-43F5-A2E6-1AC163E4C81A.1) (248F9792-7B92-4721-801E-52A51C5BEE45.1) (357393E5-F7DD-42EB-B5D9-83669D16997A.1) (87AF44E8-0B35-4F63-A490-C6AB6AFF1467.1) (285B89D6-CA5C-4D7C-B7E5-37CD4CB75472.1) (453247E1-3499-48BA-9C3E-638BB26662F2.1) (FD8C7386-88CB-4501-B8CB-99336B35A772.1) (FD473AAF-D9BF-41D5-BEAA-75FD1A0ABEE3.1) (8E45224C-FE4C-4850-89EC-28410D2C3C59.1) (20EDEB74-9B8E-46D8-8E27-62F103151532.1) (CF6DC6DF-51E8-4E7F-874E-3241112E0ADE.1) (AAAB8C4E-4FEB-43C1-82B6-AC986E4545BB.1) (76395FF7-A2DD-41B8-9333-D36AF6C72203.1) (2E87F149-CB05-4C3D-BE4C-B6333DA6E4CF.1) (A0651811-989F-4AF7-A48C-5ABAE570529C.1) (92D59FB8-1FA5-4F9F-A4D2-CB890DA0C1A4.1) (6F4322FA-7BF6-4223-AED8-9702FFB2E6A4.1) (08920FBA-DACF-40F5-971E-7E755F8106D3.1) (CFE040A7-AE16-4905-9769-C7C581C8E63D.1) (2439CE8B-C87B-4132-9EFE-C7511DB74958.1) (45141F8C-CC65-4362-8F00-5BCAF73D2D29.1) (8A911F47-886A-4E49-971A-77E7DDFD1BB5.1) (1F66EC99-4029-4076-846D-1B5ABA17E156.1) (9D5F295D-D040-4F87-B922-1A989FA7BD3C.1) (FBBC518F-6B0C-46B9-8631-1140370DEC43.1) (B0B609CC-75BF-4C68-ABCF-0BB1ED99FC33.1) (C5003280-70F5-4D70-9AA3-6A391AB507BC.1) (D83DDBCE-F6B6-4E49-9C98-CC771E33E363.1) (D6501268-56B7-4CD9-A1B2-B2A54B4098E9.1) (B074A09B-8EE7-41B7-B454-A96A7C2F1FF0.1) (523753A2-4FD5-4DBC-9411-DD46C7025E8D.1) (EF63C6DB-EA0F-4B71-A87A-2CFFEC38FAD0.1) (B822D0D8-0FFA-415E-89F5-D3145DAF7CC8.1) (34490F6E-C2AB-4869-BC49-D16ECB619CBE.1) (059D1267-EEDA-45D3-AA8C-1B0418A820CE.1) (A0F7D144-79D5-47D4-AB5E-0690736FC96E.1) (6C80D2D2-8D30-4D25-822A-59F747E51F8A.1) (A6C5BECC-5916-4FCB-BC33-514E6CB49C83.1) (19BB5264-6B86-47A5-9306-0D1F203C32C9.1) (3AA80992-4AE4-466D-A210-E909DA59DEEE.1) (E76DD255-8D2E-49A2-A826-4E157BBADB61.1) (FC1E39F7-15CE-4485-9AC0-5E63B5D758AA.1) (EE5DB8A4-F8F9-406B-A7AE-3677A015560A.1) (3EA56C37-D60B-4A9C-806E-A49E4FF405C4.1) (C7C1DD26-6A09-493D-8708-A90017DC40DA.1) (73A489ED-706C-46ED-BC1C-C2CA1ECD5B02.1) (3A1C1C13-C6FB-42F8-85B8-F60E33C0193E.1) (36B3592A-8393-42EA-A2ED-B7CE1D74197E.1) (D42C6134-C6E8-446F-9389-9A2B20F3A31B.1) (B5C91CEE-9F79-462A-927E-2969CCF9E045.1) (0BD29CF4-2C1E-4C58-856B-04F9FE91A7E3.1) (FCF6CAF5-7E44-46C8-AA66-51642891B1CE.1) (05CD4CA8-3D46-401E-A4A4-D70672148A1B.1) (E061259D-E030-420E-BE69-FFF65C69AC75.1) (EC910596-8BDA-4D4C-9EB0-61FC89BDEDB4.1) (6D47F3F5-1EFD-4C0A-9CE5-0E8A13138271.1) (108B3AEA-A6B9-469F-8868-B3F61D55BCE0.1) (BDEA9E9B-E251-4946-B2C0-352D7F03FA4F.1) (D567A3F5-9377-46A5-92DD-DE54DCAB52F5.1) (5DE73DBE-78CC-45BE-9CDE-0B0A646E8DC0.1) (D274B463-8FEC-415E-8C06-A133B993038D.1) (F6118907-1E1D-4C7F-854A-2C61A3820A60.1) (76F16163-7EEB-4533-BD58-29C5D81CA6F6.1) (395D22C7-6646-47C6-B032-7D8DD74D68A9.1) (BA5D5ADA-4A19-4B38-A00D-5DD2DF5FC88F.1) (69042D41-5836-4781-ACB7-E8228FB376D3.1) (B1E7390D-C85E-47E6-8949-2D4D62787E2B.1) (06B9DDFB-38C4-4F99-BD97-D681987426D6.1) (8B2F7F36-1637-4C48-ABB9-C300CFCFE96C.1) (6FB9108F-909F-4CE2-8B7E-8AD665D42754.1) (1E8CCE6E-88F9-4600-9CE1-C2BFC1ABB687.1) (A6977BC1-0591-4CDC-8EE0-C1844A41ACA8.1) (CD82F17D-296B-4E9D-9548-29FAA90DF855.1) (61D3DCC1-A61F-4088-BC41-874E88C1BE8E.1) (ED68F755-5309-4FB0-B841-DC8084950F2D.1) (6B3BDDBB-2245-4469-B465-6E1E97787FE6.1) (14973739-8626-421B-8698-C22B41A9B9F9.1) (3DD89839-BB47-4C85-96B3-703F83E0FAED.1) (79026D2E-B886-4BE1-B10C-EFE313B59423.1) (C0C8DFE5-3600-4AFC-8466-298D8B50C56F.1) (78E607A2-D272-48DB-B666-68B92D5A89FB.1) (F5645015-DA25-45B6-9D58-411DEF41F342.1) (C16414CD-D487-4339-B4D0-931F23292DF0.1) (3C773AFA-20C6-458D-908A-0F084229C63F.1) (66C4F0E8-B949-4BF7-AF22-AC78C9594B2F.1) (499F343D-BB10-445E-A1C5-4E112275DEDC.1) (8D9A1EF5-1755-4EC5-8C58-26C61CCA9B4D.1) (0DE2CEF8-C679-4F0C-B15A-A5D6E57BFD28.1) (659EFAA8-FEA9-43A1-B13B-0E6400A14972.1) (BB2BC712-914E-4475-9242-4E520B14D545.1) (89E3511F-CDDF-4B6A-8A70-0FAC0EFF876D.1) (E395E6DD-59A4-465A-A902-BDBB4CF90A0F.1) (9CDBB8F7-D83C-48D1-9F26-E93B9B903C84.1) (94977DF1-3AC5-41D6-A892-81952BD06233.1) (17CB8157-2B74-44A6-B703-043256A56E11.1) (B53D5DB1-AB84-4A96-9200-E588099DF742.1) (A64CC95B-C927-4B8E-A6CA-4536C7302518.1)

I just tried to send an email to my new configured server (I'm new to this) and I got that. What could be the cause?
I love that project. I hope to been able to use it in production.

**Comment by Dexus** [comment]
Which plugins are active? What settings you have made?

**Comment by 0vermind** [comment]
I followed the video tutorial.
all settings are as default and untouched except for the host_list which is set as my domain.net and the listening port on 25.

**Comment by Dexus** [comment]
What for a video tutorial?

This one? https://www.youtube.com/watch?v=6twKXMAsPsw

To clearify what is the problem i need LOGFILES and content of __/config/plugins__.
__/var/log/haraka__ or/and __/var/log/syslog__

**Comment by 0vermind** [comment]
Yes I followed that video.
there are no log in this dir. I assume the log s are not enabled by default in the conf.
config/plugins is empty. Only one dir "auth" is present but empty.

I think I will use a different service online instead configuring my own haraka server for now.
Thanks for replying me and keep the good work :), sorry but I am in hurry for  this specific work, I will try again in the future with more time.
