### ISSUE TITLE
How to modify message body?

### ISSUE THREAD

**Issue by melissamanrique** [baudehlo/Haraka#1155]
I'm writing a plugin to modify the text in the message body. I can't use `connection.transaction.add_banner()` because I need to modify strings in the middle of the body. 

I've tried doing something like: 
```javascript
exports.hook_data = function (next, connection) {
    connection.transaction.parse_body = 1;
    next();
}

exports.hook_data_post = function (next, connection) {
    connection.transaction.body.bodytext =  getNewBody();
    next();
}
```
But it keeps sending the email only with the original body. 

I've read the documentation and I haven't been able to find it. Can you help me?

Thank you!

**Comment by smfreegard** [comment]
Sorry - but you can't do what you are attempting to do.

body.bodytext is a decoded copy of the input message and is only used for plugins to read the decoded data (e.g. check the bodytext for specific strings or URIs).

There is no provision in Haraka to replace the input stream with other data at present.

**Comment by melissamanrique** [comment]
What a shame

Would you accept a PR with a function for doing so? A function like `connection.transaction.set_banner()` available for plugins which could modify body?

**Comment by smfreegard** [comment]
I'd forgotten about transaction.add_body_filter(ct_match, filter) in https://github.com/baudehlo/Haraka/blob/master/docs/Transaction.md - it might do what you need.

We're always open to PR's for new functions.

**Comment by melissamanrique** [comment]
Hello. We tried something like this and could get anything. Any idea?

````js
exports.hook_data_post = function (next, connection) {

  connection.transaction.add_body_filter('text/html', function (content_type, encoding, body_buffer){
    return new Buffer("<p>New text</p>");
  });

  return next();
}
````

We also tried with /^text\/html/ instead of 'text/html' and does not work.

Thank you @smfreegard.

**Comment by smfreegard** [comment]
hook_data_post is too late, you must set this in hook_data.

**Comment by melissamanrique** [comment]
I've also tried in hook_data and doesn't work either. The server gets hanged after receiving data and the connection dies after a 30 segs timeout.

Is there something I'm missing?

**Comment by smfreegard** [comment]
Just a guess - but if you're replacing everything, make sure you send an
SMTP end of data e.g.  \r\n.\r\n

**Comment by melissamanrique** [comment]
You're totally right! My bad. 

I assumed it was hanging on receiving message from client. Not sending it. 

Thank you very much.
