### ISSUE TITLE
MX without A records

### ISSUE THREAD

**Issue by ruandao** [baudehlo/Haraka#1159]
I write a plugin to forward some email  to another email according database.

the code simplest like the following: 

    exports.hook_rcpt = function (next, connection, params) {
	var rcpt = params[0];
        
        if (rcpt.host == "xxx.com") {
            it.logwarn("====skdlf");
            var address = // get address from database according rcpt.user
            var toAddress = new Address('<' + address + '>');
	    connection.transaction.rcpt_to.pop();
	    connection.transaction.rcpt_to.push(toAddress);
	    connection.relaying = true
	    next(OK);
	    return;
        }
       next(DENYSOFT, "not found user account");
    }

but, it seem the server never run into any code in the above.
and i get the following error : 

    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8] [access] pass:unlisted(conn)
    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8] [access] pass:unlisted(conn), connect:any
    [ERROR] [38A98778-D1E0-4064-AF11-0A54720063A8] [dnsbl] no zones
    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8] [access] pass:unlisted(conn), connect:any, helo:any
    [ERROR] [38A98778-D1E0-4064-AF11-0A54720063A8] [helo.checks] forward_dns(Error: queryA ESERVFAIL smtpbg63.qq.com.)
    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8.1] [access] pass:unlisted(mail)
    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8.1] [access] pass:unlisted(conn), connect:any, helo:any, mf/rt:any
    [INFO] [38A98778-D1E0-4064-AF11-0A54720063A8.1] [core] hook=mail plugin=mail_from.is_resolvable function=hook_mail params="<xxxxxxx@qq.com>" retval=DENY msg="MX without A records"
    [NOTICE] [38A98778-D1E0-4064-AF11-0A54720063A8.1] [core] sender <xxxxxx@qq.com> code=DENY msg="MX without A records"
    [NOTICE] [38A98778-D1E0-4064-AF11-0A54720063A8.1] [core] disconnect ip=103.7.29.150 rdns="smtpbg63.qq.com" helo="smtpbg63.qq.com" relay=N early=N esmtp=Y tls=N pipe=N txns=1 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="550 MX without A records" time=10.166
    [NOTICE] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [core] connect ip=14.17.32.37 port=38176 local_ip=:: local_port=25
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [access] pass:unlisted(conn)
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [access] pass:unlisted(conn), connect:any
    [ERROR] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [dnsbl] no zones
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [access] pass:unlisted(conn), connect:any, helo:any
    [ERROR] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A] [helo.checks] forward_dns(Error: queryA ESERVFAIL smtpbg326.qq.com.)
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A.1] [access] pass:unlisted(mail)
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A.1] [access] pass:unlisted(conn), connect:any, helo:any, mf/rt:any
    [INFO] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A.1] [core] hook=mail plugin=mail_from.is_resolvable function=hook_mail params="<xxxxxxxxxx@qq.com>" retval=DENY msg="MX without A records"
    [NOTICE] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A.1] [core] sender <xxxxxx@qq.com> code=DENY msg="MX without A records"
    [NOTICE] [5EE4F7EA-7003-4E28-80BC-26A0E0B1CB1A.1] [core] disconnect ip=14.17.32.37 rdns="smtpbg326.qq.com" helo="smtpbg326.qq.com" relay=N early=N esmtp=Y tls=N pipe=N txns=1 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="550 MX without A records" time=10.901

sorry for lack of the knowledge about email server, but what's the key point to solve the problem, I hope to create a forward server

thank you.

**Comment by smfreegard** [comment]
Your DNS configuration is broken.  A lookup of qq.com is returning SERVFAIL.

**Comment by ruandao** [comment]
thank you  

In fact, when i change to another server, this error was not display, may be I change something else
However I still never understand it, why my dns configuration will afect the lookup of qq.com, my dns was something about my domain
