### ISSUE TITLE
block more attachment file types

### ISSUE THREAD

**Issue by msimerson** [baudehlo/Haraka#1184]
Update our list with what seems to work well for **a very large** fraction of the worlds mailboxes:

[Google: some file types are blocked](https://support.google.com/mail/answer/6590?hl=en)

.ade, .adp, .bat, .chm, .cmd, .com, .cpl, .exe, .hta, .ins, .isp, .jar, .jse, .lib, .lnk, .mde, .msc, .msp, .mst, .pif, .scr, .sct, .shb, .sys, .vb, .vbe, .vbs, .vxd, .wsc, .wsf, .wsh

**Comment by Dexus** [comment]
:+1:
