### ISSUE TITLE
Is it bad idea to use host_list where we update hosts often?

### ISSUE THREAD

**Issue by ashwinreddymekala** [baudehlo/Haraka#1195]
It looks like host_list file update is automatically reloaded by Haraka, is it bad idea to use host_list to accept incoming mails where we update hosts often.
Will there be any issues while Haraka reloading? or should we use database instead of host_list for this lookup.

**Comment by Dexus** [comment]
Please define often...

if you update your host_list, haraka reload only the host_list file, so its okay.

**Comment by smfreegard** [comment]
The only 'gotcha' with updating things like host_list in Haraka is that you should do it in two steps e.g.

`````
build_new_file > /etc/haraka/config/host_list.new
mv /etc/haraka/config/host_list.new /etc/haraka/config/host_list
`````

This is to ensure that when Haraka reloads the file - it doesn't get a partial read.

The other issue with file based reloading is that it's done using fs.readFileSync which is a synchronous function, so if the file is large (MBs) and you're reloading it often (multiple times per minute), it won't perform as well as getting the data using async functions from a database like Redis.

**Comment by ashwinreddymekala** [comment]
@Dexus we may update 400 times/day ( this is maximum we expect )

@smfreegard instead of reloading file we're looking Redis ( we're already using it ).

all hosts are sub domains of our domain. are there any other work around for this special case ( i.e sub domains ) which you suggest.

**Comment by smfreegard** [comment]
> all hosts are sub domains of our domain. are there any other work around for this special case ( i.e sub domains ) which you suggest.

Not really - you'll only want Haraka to accept mail for sub-domains that you're happy to receive mail for, so you'll need to maintain a list somewhere.   Redis is a good choice.
