### ISSUE TITLE
Maximum size limit

### ISSUE THREAD

**Issue by ricardopolo** [baudehlo/Haraka#1202]
Hello. We use haraka to send an email from Office 365, check some things in Haraka and then return to Office 365 for delivery.

I works pretty well.

But if the email has an attachment of more than 1 Mb it fails. 

We havent change the default settings in Haraka or have limits in Office 365.
Where should I look?

![image](https://cloud.githubusercontent.com/assets/1263856/10313294/95495d7a-6c14-11e5-9831-c2105a6eb4ee.png)

I found an issue with the same error https://github.com/baudehlo/Haraka/issues/31
Thank you.

**Comment by smfreegard** [comment]
See `config/databytes` which is the maximum size in bytes of a message that Haraka will accept.

**Comment by ricardopolo** [comment]
Thanks @smfreegard for the answerr. The current value `config/databytes` is the default 500000, which I think it is 50Mb.

As you see I get a message with a much lower limit.

**Comment by baudehlo** [comment]
That's 5MB.

**Comment by smfreegard** [comment]
Are you sure you're looking at the right `config/databytes` file then?  You should be looking in the directory that you ran `haraka -i /path/to/install` when you initially installed Haraka.

You can check the limit being advertised by running `telnet localhost 25` and then typing `EHLO my.host.name` and it will be reported under the `SIZE nnnnnn` value (in bytes) e.g.:

`````
[root@mx1 DefenderMX]# telnet localhost 25
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 mx1.fsl.com ESMTP DefenderMX 2.6.1 ready (FFFFCE82-4E39-421B-A52E-EA23E9C5422F)
EHLO mx1.fsl.com
250-mx1.fsl.com Hello localhost.localdomain [::1]
250-PIPELINING
250-8BITMIME
250-SIZE 52428800    <---- HERE
250-STARTTLS
250 XCLIENT NAME ADDR PROTO HELO LOGIN
QUIT
221 mx1.fsl.com closing connection. Have a jolly good day.
Connection closed by foreign host.
`````

As you can see - my limit is 50Mb.

**Comment by smfreegard** [comment]
Actually @baudehlo - that's not 5Mb it's 500Kb.

**Comment by ricardopolo** [comment]
All right, it's 500kb, thats the issue.

Dont you think this is too small to be the default value?

**Comment by smfreegard** [comment]
Yes - we've already addressed that in the version to be released shortly.   It's now 25Mb by default.
