### ISSUE TITLE
Tutorial request - Setting up Haraka on one server for several domains

### ISSUE THREAD

**Issue by kokujin** [baudehlo/Haraka#272]
Harakas documentation seems to very good, but I think it lacks the very basic stuff for newbies like me. Is there some guide or tutorial that explains how I can setup haraka to to send a rely mail for multiple domains on my server? Thanks

**Comment by Dexus** [comment]
@msimerson can this be closed?

**Comment by msimerson** [comment]
Install guides for Ubuntu and FreeBSD are listed in the wiki[https://github.com/baudehlo/Haraka/wiki]
