### ISSUE TITLE
Add Coffee-Script Support for Plugins

### ISSUE THREAD

**Issue by danhstevens** [baudehlo/Haraka#315]
It would be super helpful if Haraka would look for files in the plugin directory with a `.coffee` extension if no `.js` extension of the same name is found. I write all my plugins in coffee-script and it's messy to have to require two files for each plugin I write (the original `.coffee` and its `.js` counterpart).

**Comment by msimerson** [comment]
This is unlikely to happen based on an Issue. Per comments in this thread, PRs will be considered.
