### ISSUE TITLE
Syntax error in address failure

### ISSUE THREAD

**Issue by dontforget** [baudehlo/Haraka#387]
I'm having trouble with a small DoS on my Haraka.

Here's the full log:
https://gist.github.com/dontforget/f88ffdbdcd297387aba0

When this happening Haraka can't receive any more emails because 
Haraka processing all of the email addresses starting from 0 and going up to few thousands.

Thanks.

**Comment by msimerson** [comment]
@smfreegard "Unparsable MAIL commands will still not call the hooks though, so it's still an issue. They respond() directly."
@baudehlo "We should have a "max_errors_before_disconnect" setting. similar to max_unrecognised_commands"

**Comment by msimerson** [comment]
> @baudehlo "We should have a "max_errors_before_disconnect" setting. similar to max_unrecognised_commands"

We have a max_errors limit now, in the new `limit` plugin.
