### ISSUE TITLE
configfile: watch bug

### ISSUE THREAD

**Issue by smfreegard** [baudehlo/Haraka#470]
I noticed this at the weekend when I added a config/smtpgreeting file to one of my systems which did not exist previously.

Since the change to fs.watch in https://github.com/baudehlo/Haraka/commit/4f577f3958539f02249caa04849351648de26070 Haraka caches results from files which do not exist and therefore it never notices if these files are created later as fs.watch cannot watch files that do not exist and therefore requires a restart to see the changes to these files.

Possible fixes:

1) Watch the config *directory* instead of each of the files

Advantages: only one watcher required instead of one per file
Disadvantages: will only work on Linux and Windows as per fs.watch docs as the 'filename' attribute is required for this to work correctly.

Maybe we could 'switch' this based on process.os?

2) If ENOENT is returned by fs.watch - add a watcher using fs.watchFile instead

Once the file is created we would unWatchFile and switch to fs.watch

3) Remove cache entry if ENOENT is returned (slower)

**Comment by msimerson** [comment]
@smfreegard , should this issue be closed now?

**Comment by smfreegard** [comment]
Yup - it's fixed.
