### ISSUE TITLE
Get bannering working again

### ISSUE THREAD

**Issue by baudehlo** [baudehlo/Haraka#587]
Craigslist have been testing bannering and say it is now stable.

It relies on this patch: https://github.com/baudehlo/Haraka/commit/b6a5289db0737e3ea03ad4965f897b5ba35ed1f8

Open issues:

* message_stream is (normally) a stream of Buffer objects. This changes it to a stream of strings in bannering mode. How much does that possibly break?
* It changes the place where message_stream.add_line_end() is called. Does this affect anything?

And any other issues we can discuss on this ticket.

Note: No intention to re-enable until after 2.5.0 is released.

Tagging @smfreegard for his attention.

**Comment by msimerson** [comment]
I'm pretty sure that the code contributed by @chazomaticus closes this issue?

**Comment by chazomaticus** [comment]
Not sure what this was about--seems like bannering has been working great for a while.
