### ISSUE TITLE
Bounce hook is not called when error 550

### ISSUE THREAD

**Issue by gowthamsettu** [baudehlo/Haraka#638]
Hi,
I'm try to log the bounce mail. 
Bounce hook is not called when the not valid email id.But it called when the domain is not valid.But bounce mail can be received.
First not valid domain : mail subject is "Failure notice"
valid domain not valid email address: mail subject is "Undeliverable".
Thanks in advance

Thanks,
Gowthamsettu

**Comment by celesteking** [comment]
I'm lost in translation. 

Do you mean ```hook_bounce``` doesn't get called for a bounce mail that is bounced by remote server? But hey, why would it be called, the message will just be discarded (AFAIK) and story ends right there.

**Comment by baudehlo** [comment]
I think this issue has been sitting open and nobody else experiencing anything like it, so can just be closed unless anybody else sees it. Closing as not an issue.
