### ISSUE TITLE
can't install on node v0.11 (node-syslog)

### ISSUE THREAD

**Issue by xpepermint** [baudehlo/Haraka#677]
I saw a comment inside travis file but I have servers running the latest node release thus it would be great to fix that.

**Comment by msimerson** [comment]
UPDATE: iconv builds successfully on node 0.10. There's also a PR #818 which will install iconv-lite instead, which also works. The pending issue with node 0.12 support is node-syslog. Haraka will run on node 0.12 and iojs (the latter, not tested) but the log.syslog plugin will not.

**Comment by chazomaticus** [comment]
FWIW, I've got a [syslog2 branch](https://github.com/chazomaticus/Haraka/compare/syslog2) that adds a log plugin using syslog2.  I haven't written any tests for it yet.  In fact I don't think I've even tried running it yet, but it might still be a good starting point for (optionally) moving away from node-syslog.

**Comment by msimerson** [comment]
````
10:57:30 AM chazomaticus: would it be better to just replace log.syslog to use syslog2, or give it a new name?
10:57:58 AM ultimatt: If I were doing it, my first thought would be to supporting both (if it wasn't very hard)
10:58:00 AM godsflaw: count me in as three
10:58:28 AM ultimatt: on new installs, default to syslog2, but if you cant load it, then try 'node-syslog'
10:58:29 AM chazomaticus: :D
10:58:38 AM ultimatt: that makes the upgrade path really painless
10:58:43 AM chazomaticus: that sounds good
````

**Comment by smfreegard** [comment]
I also ran into this yesterday: https://github.com/phuesler/ain which also looks good.

**Comment by msimerson** [comment]
This problem is worked around as of PR #869 . Haraka now installs the log.syslog plugin works on node 0.10, 0.12, and iojs.
