### ISSUE TITLE
base class for Redis

### ISSUE THREAD

**Issue by msimerson** [baudehlo/Haraka#726]
Haraka might benefit from a base class for Redis. Rather than having each plugin do common things like require('redis'), redis_connect(), redis_ping(), have those implemented in a base class that can be inherited.

**Comment by celesteking** [comment]
DB indexes? Sounds good. How about allowing a plugin have a separate redis config?

for ex.: redis.ini:
```ini
[default]
host = 1.com
port = 1234
db = 0

[karma]
host = localhost
db = 1
password = xxx

[queue/random_delivery]
port = 12354
```

**Comment by smfreegard** [comment]
Indeed; you might want one plugin to use in-memory and another to use Redis too.

Equivalent functionality can easily be achieved by adding a Redis plugin and exporting it via server.notes to plugins that want to use it (which is what I do here).

**Comment by msimerson** [comment]
considering this done with the merge of plugins/redis.
