### ISSUE TITLE
disable TLS negotiation for remotes that fail STARTTLS

### ISSUE THREAD

**Issue by msimerson** [baudehlo/Haraka#770]
# the idea

If a remote attempts to connect and fails, cache their IP in an in-memory no-tls object. The next time that IP connects:

* don't offer STARTTLS
* remove their IP from the no-tls object

This would:

* permit mail to make it though from MTAs and MUAs with old/broken SSL/TLS implementations
* permit Haraka to require more secure TLS settings with less impact
* automatically enable TLS when those hosts fix/upgrade their TLS

**Comment by wioxjk** [comment]
> ```ini
> disable_for_failed_hosts=true
> ```

Hi,

Just found this after spent way to many hours looking for a similar solution for my problem in the docs.
Would it be possible to include this in the official docs?
This seems to still work with 2.8.28

**Comment by msimerson** [comment]
> Would it be possible to include this in the official docs?

A PR is welcome.

**Comment by wioxjk** [comment]
> > Would it be possible to include this in the official docs?
> 
> A PR is welcome.

Sure, I'll try to get it done as soon as I have figured it out :)

I just encountered this:

`2022-04-28T12:35:22.217Z [ERROR] [43200577-AD5B-4A9C-B6EA-0A8C23F93441.1.1] [outbound] Ongoing connection failed to 194.112.1.114:25 : Error: 140012605945728:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2158:`

It does not seems like this is helping out in this particular case? The mail is not delivered sadly

**Comment by msimerson** [comment]
> dh key too small

Hmmm, wonder what that means.
