### ISSUE TITLE
Send email using external smtp server

### ISSUE THREAD

**Issue by blackrosezy** [baudehlo/Haraka#835]
Hi, I cannot find any example in Haraka to send email using external smtp, something like this https://www.linode.com/docs/email/postfix/postfix-smtp-debian7

I have tried to understand smtp_proxy and smtp_forward plugin, but not sure where to put the smtp username and password.

**Comment by msimerson** [comment]
See the [smtp_forward](https://github.com/baudehlo/Haraka/blob/master/docs/plugins/queue/smtp_forward.md) doc page for instructions for using username and password.
