### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by baudehlo** [baudehlo/Haraka#842]
I think we're good to release 2.6.0 now.

Anyone with thoughts, objections, or +1s?

**Comment by msimerson** [comment]
I would pull in #838 for two reasons:
1. Haraka builds currently fail b/c of iconv on node 0.8. That PR tweaks to .travis.yml to permit build failures on 0.8.
2. It makes a couple small changes to the tests so they pass on Windows.

Other than that, full steam ahead!

**Comment by baudehlo** [comment]
I'm fine with that PR. Can't merge from my phone so feel free to do so.

Any input from others?

**Comment by msimerson** [comment]
You might want to check out the CodeHub app. It's handy that way. :-)

**Comment by baudehlo** [comment]
Just did. Not bad but horrible UI. It's probably easier for me to get off my lazy ass and open my laptop to merge stuff :)

**Comment by baudehlo** [comment]
I'm just waiting on @msimerson to get back from vacation now to see if he updates Changes manually or via a git command. Other than that we're ready to release.

**Comment by msimerson** [comment]
He's bbbbaaaaaacckkkk. When I updated Changes, I did it manually, by reading the commit logs and summarizing them into bullet points.

**Comment by baudehlo** [comment]
Got any time to do it again? ;)

**Comment by msimerson** [comment]
PR #853 is open.

Reading the commit logs isn't a ton of fun. To come up with a halfway decent summary, I had to click and review quite a few of the commits and PRs in order to figure out what they were doing. It's be great to have a way to automatically populate Changes. The only way I can see that happening is if we committers were disciplined with PRs, squashing them before merging and making the first line of the commit message suitable for direct inclusion into Changes as a bullet point. That *is* the prescribed way to use git, but it might be a bit too anal. Probably the only way to get everyone to agree it's worth doing is to alternate turns keeping Changes up-to-date. After everyone has done it manually a few times, raising the bar on "git cleanliness" would probably be an easy sell.

**Comment by baudehlo** [comment]
Thanks for that. This usage of git is totally new to me and I would love to make this whole thing easier too. I've only been using git since starting Haraka and have probably never been using it 100% properly. I need to invest some time on it. Thank you!

**Comment by msimerson** [comment]
> This usage of git is totally new to me

I too am learning git as we go. I'm getting a lot more experience with it on other projects with more frequent release cycles. I'm every bit as guilty of submitting sloppy PRs or commits that aren't much fun to "summarize" months later when the details have fled short-term memory. The pain of that sloppiness is infrequent (once per release, and when searching through the commit history for other purposes) whereas asking everyone to "up their game" a bit when submitting PRs is frequent. It may not be worth the effort. I just can't think of any other way we could automatically update Changes.

**Comment by baudehlo** [comment]
Ok we can all make an effort then to comment on PRs to merge changes. By the looks of things git should be pretty flexible even if we have to rewrite history a bit.

Regardless, I'll try and get 2.6 out tomorrow.

**Comment by msimerson** [comment]
Git is flexible, and history rewriting can be done locally, but we can't rewrite the history of baudehlo/master without messing up every copy of the repo that is checked out.

**Comment by godsflaw** [comment]
Looks good, so +1.  I personally am in favor of squash merging to get a
better automated changelog, but let's not push back on new/casual
contributors too much for this.  It would be better to keep the bar low for
contributing and squash those PR ourselves.

BTW, sorry I've been incommunicado.  I've been spending most of my time
with our new baby girl.  I should be shifting more time to my projects and
less towards the noob as she starts to figure this world out.

**Comment by baudehlo** [comment]
2.6.0 is out!

**Comment by smfreegard** [comment]
Well done everyone!
