### ISSUE TITLE
Is there any way to send mails from "Haraka" and receive from "Postfix"?

### ISSUE THREAD

**Issue by varmad** [baudehlo/Haraka#851]
Hello,

Is there any way to send mails from "Haraka" and receive from "Postfix"?

Thamks,
Varma

**Comment by smfreegard** [comment]
Put Haraka on a different port and tell whatever you need to send mails with to use that port instead?

**Comment by msimerson** [comment]
Yes.

There are many ways to do that. Please feel free to ask this question again more specifically so that we can provide more specific and more helpful answers.

**Comment by varmad** [comment]
Hello,

1. I have a Postfix installation with devcot which is runnig on port 25 and I have users as well.
2. On the same server I have installed Haraka which is runnig on port 587 and I can able to send emails .
3. Now I need to send emials with Haraka using Postfix user credentials, is this possible?


Thanks,
Srinivasa Varma

**Comment by smfreegard** [comment]
Yes - that is possible; see the auth_proxy plugin and documentation.  That will do exactly what you want.
