### ISSUE TITLE
Warnings on Haraka startup

### ISSUE THREAD

**Issue by steowens** [baudehlo/Haraka#856]
DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
[WARN] [-] [dnsbl] zone 'zen.spamhaus.org' did not respond to test point (null)
[WARN] [-] [dnsbl] disabling zone 'zen.spamhaus.org'

Not sure what these warnings are trying to say but they sure look ominous.

**Comment by baudehlo** [comment]
That is generally because you are blocked from querying spamhaus. This usually happens because you are using your ISPs DNS servers. Installing a local caching nameserver will fix that and will also help your performance.

**Comment by steowens** [comment]
Thanks
