### ISSUE TITLE
Maybe: https://github.com/baudehlo/Haraka/issues/777

### ISSUE THREAD

**Issue by steowens** [baudehlo/Haraka#857]
I am getting

DEBUG] [EA1C1A9F-89CD-4B09-A667-105202FBC1C6.1] [core] running disconnect hooks
[NOTICE] [EA1C1A9F-89CD-4B09-A667-105202FBC1C6.1] [core] disconnect ip=24.18.98.14 rdns="c-24-18-98-14.hsd1.wa.comcast.net" helo="se-steowens-mb1" relay=Y early=N esmtp=Y tls=Y pipe=N txns=1 rcpts=1/0/0 msgs=0/1/0 bytes=232 lr="452 plugin timeout" time=30.83

sending email with swak
Is the same issue that was fixed in Dec 2014?  If so what can I do to get my installation up to snuff.

**Comment by smfreegard** [comment]
Not enough information here.   We'd need to see the full log for the session 'EA1C1A9F-89CD-4B09-A667-105202FBC1C6' to be able to tell which plugin timed out and to be able to advise you further.
