### ISSUE TITLE
SMTP Authentication on smtp_forward and smtp_proxy not working

### ISSUE THREAD

**Issue by salvop** [baudehlo/Haraka#871]
SMTP authentication on smtp_forward and smtp_proxy is not working, smtp queue are always started without issuing authentication to relay provider. Also documentation is lacking on this.

Module is almost useless without authentication to relay.

**Comment by smfreegard** [comment]
Ok - I've just read the code and yes, the docs haven't kept up with the features added and the multi-domain configuration that was added has really confused how the authentication works.   Can you confirm that the following in smtp_forward.ini or smtp_proxy.ini works for you.

````
host=1.2.3.4

[auth]
type=plain
user=auth_username
pass=auth_password
````

and can you also try this:

````
host=1.2.3.4
auth.type=plain
auth.user=auth_username
auth.pass=auth_password
````

Let me know and I'll document it.

**Comment by smfreegard** [comment]
Actually - I think the latter example won't work at all, but if you can confirm that please.

**Comment by salvop** [comment]
I tried and in both cases auth data are not passed to smtp client.

**Comment by smfreegard** [comment]
Can you gist your smtp_forward.ini file please?

**Comment by salvop** [comment]
host=smtp.sendgrid.net
port=587
[auth]
type=plain
user=user
pass=pass

**Comment by duanefields** [comment]
Hmm, this wasn't working for me, so either I'm missing something or it wasn't working - for the moment I've patched this in my branch, https://github.com/glg/Haraka, but I probably don't know enough to do this "correctly"... anyway, it case it's useful to someone...

**Comment by vivek779** [comment]
Hi i was working on smtp_proxy plugin it works fine but i am not able to figure out how to set two or more server for sending proxy .Suppose i have 3 server A,B,C i want to send proxy on both server B,C I have mentioned host user and password of both server but it is sending proxy on single server could anyone please guide how it will send proxy to both server and in which manner it will send proxy

**Comment by vivek779** [comment]
HI i was working on smtp_proxy plugins it works fine for single server but i am not able to send  proxy  on multiple servers whenever i mentioned multiple smtp server ip and credentials on that  smtp_proxy.ini the server keep sending proxy on the single server only .How would it send proxy on multiple server  please guide
