### ISSUE TITLE
Manual Outbound Email not DKIM signed

### ISSUE THREAD

**Issue by garyns** [baudehlo/Haraka#880]
Sending an email using outbound.send_email(form, to, contents) does not get signed. Should it / can it?'
Thanks.

**Comment by baudehlo** [comment]
Unfortunately it doesn't go through the plugins, so doesn't get signed. The
only way to do it (right now) is use something like nodemailer to do a full
SMTP connection through your server and send an outbound mail (relay it
somehow).

We do kind of consider it a bit of a bug, but it's tough to fix.

**Comment by garyns** [comment]
Thanks nodemailer was my backup plan. I'll proceed with it.
