### ISSUE TITLE
Embedding images in banner

### ISSUE THREAD

**Issue by garyns** [baudehlo/Haraka#881]
Not an issue, but a vote for a feature, or a callout to anyone who might know how I can achieve image embedding, if at all.

I'm using Haraka with an Exchange server and Domain Controller to stamp a dynamically generated signature/banner to all outbound emails.

I'd like to be able to embed the banner's images in the outbound email.

Thanks.

**Comment by msimerson** [comment]
I presume you're using `transaction.set_banner()` to add the banner? 

To embed an image in a HTML message, you need to attach the image to the message as a MIME part, and then reference that part in your HTML. You may also have to change the HTML MIME type from `text/html` to `multipart/related` in order to get the ID references to display the embedded image properly.

**Comment by garyns** [comment]
Thanks. Yes I am using transaction.set_banner(). I though I'd have to end up manipulating the email. I just wanted to check I wan't missing another way.

**Comment by msimerson** [comment]
The "other" way I know of is store the image on a HTML accessible location and service them via HTTP, but that's not embedded any more. :)

**Comment by garyns** [comment]
Yes, that's how I'm currently doing it at the moment. But that results in the images not showing in some clients (= outlook) with a message related to protecting privacy and the need to manually initiate the image download. My organisation does not like that. I understand this can happen with embedded images also, but seems based on experience to be rare.

**Comment by garyns** [comment]
What's the best way to manipulate/add to an email message? I've hacked around and browsed through the source for a few hours without any success.

connection.transaction.add_data() looked promising, but I can only get it to insert raw data at the start of the email (in an early hook like hook_mail), but never was able to append raw data at the end.

Thanks.

**Comment by chazomaticus** [comment]
There's one other way I know of to embed images in email HTML, supported in many clients but maybe not all: [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme).  Not sure if that's an option in your case, but wanted to mention it.

As far as manipulating an email, I've done a little work toward that end, but only in munging individual MIME parts, never the entire thing at once.  See Transaction.add_body_filter in master.  Not sure if that could be extended to add MIME parts or change the structure.

**Comment by garyns** [comment]
Thanks. I looked into this method, but client support is scratchy. I found GMail displays the raw base64 data, and Outlook (at least 2011 on the Mac) actually removes the image altogether. I'll look into the filter(). Thanks again.

**Comment by CmdLnInt** [comment]
Hi garyns, did get this to work?

**Comment by garyns** [comment]
Hi,

Yes I did. After some trial and error, I discovered
that connection.transaction.set_banner() needs to be called before
hook_data_post

Gary.
