### ISSUE TITLE
550 Authentication required Error when using tls

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#885]
Hi,

I have configure haraka with tls but unfortunately there is some problem as mention below -
1. When I have send email using 'swake' without using -tls option then it shown "Host did not advertise authentication"
2. When I have using swake with -tls option then email deliver but it shown an error in logs - "secured: cipher=AES256-GCM-SHA384 version=TLSv1/SSLv3 verified=false error="Error: UNABLE_TO_GET_ISSUER_CERT"" and email header shown "(version=TLSv1/SSLv3 cipher=AES256-GCM-SHA384 verify=NO);"
3. When I have send email using SendBlaster then it connect properly and also SendBlaster logs show that "250 TLS Successful". And email header shown same logs.
4. The main issue with my application which is make in php. It not connection properly and shown error "550 Authentication require" as below -
![screenshot from 2015-03-23 12 47 27](https://cloud.githubusercontent.com/assets/11587328/6775778/437c6eae-d15c-11e4-9fc5-a5503f5b325e.png)

**Comment by smfreegard** [comment]
Based on your log output and the error you are getting - you must be trying to use port 587 which as the message suggests, requires some sort of authentication - either by IP address (using the relay plugin) or via an SMTP AUTH plugin *and* TLS e.g. using the auth/flat_file plugin and creating a username/password combo that you tell swaks or your app to use.

Alternatively - you could just use port 25 and the relay plugin.

**Comment by sym786** [comment]
Thanks for quick revert.
However I have already used port 587. And also used same detail which is I have mention in 'auth_flat_file'. Here I have also attached screenshot for same. But error is still exists. 
![screenshot from 2015-03-23 14 28 24](https://cloud.githubusercontent.com/assets/11587328/6776826/775475de-d169-11e4-8271-32bd34174c38.png)

![screenshot from 2015-03-23 14 26 53](https://cloud.githubusercontent.com/assets/11587328/6776827/7bd1c76a-d169-11e4-9de0-40cc2536100e.png)

**Comment by smfreegard** [comment]
Well either you haven't loaded the plugin (typo maybe) - you need to make sure that you have `auth/flat_file` in `config/plugins` OR the application isn't sending the AUTH command for some reason.

If you set `config/loglevel` to LOGPROTOCOL, then your logs will show you exactly what is happening.

**Comment by sym786** [comment]
Hi,

I have already set these things already. For reference kindly check attached screenshot.
![screenshot from 2015-03-23 14 58 53](https://cloud.githubusercontent.com/assets/11587328/6777191/322eefda-d16d-11e4-9662-0c3e0b05ed45.png)

Here I have also attached logs screen-shot. as below -
![screenshot from 2015-03-23 15 00 44](https://cloud.githubusercontent.com/assets/11587328/6777228/78ef95aa-d16d-11e4-9932-6e72b8a8331a.png)

Thank You.

**Comment by sym786** [comment]
Early I have used postfix and there is no any issue of such type but now with I have check everything from our end but can't get solution. So please guide me.

**Comment by smfreegard** [comment]
The screenshot you provided shows no STARTTLS command being sent by the client and because of that no AUTH capability is advertised and therefore no AUTH command being sent either.

Whatever is trying to send the message is not attempting to do it over an encrypted channel.

**Comment by sym786** [comment]
Thank You for guide and support.
