### ISSUE TITLE
Crash when sending bounce mail

### ISSUE THREAD

**Issue by carlpett** [baudehlo/Haraka#891]
Hi,
I'm having an issue where Haraka crashes when trying to send bounces. For instance, when I send a mail from my gmail address to a non-existing user at my domain, the log says this before crashing:

> 2015-03-28T11:40:56.929Z [INFO] [D27AA805-17A5-446B-9B3D-820943B4A76D.1] [outbound] Looking up undefined records for: gmail-smtp-in.l.google.com
> 2015-03-28T11:40:56.934Z [CRIT] [-] [core] TypeError: Cannot set property 'immediately' of undefined
> 2015-03-28T11:40:56.934Z [CRIT] [-] [core]     at query (dns.js:159:26)
> 2015-03-28T11:40:56.934Z [CRIT] [-] [core]     at Object.exports.resolve (dns.js:188:12)
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at HMailItem.try_deliver (/usr/lib64/node_modules/Haraka/outbound.js:939:9)
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at HMailItem.found_mx (/usr/lib64/node_modules/Haraka/outbound.js:891:14)
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at /usr/lib64/node_modules/Haraka/outbound.js:786:15
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at process_dns (/usr/lib64/node_modules/Haraka/outbound.js:823:13)
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at /usr/lib64/node_modules/Haraka/outbound.js:833:13
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at asyncCallback (dns.js:68:16)
> 2015-03-28T11:40:56.935Z [CRIT] [-] [core]     at Object.onanswer [as oncomplete] (dns.js:147:9)
> 2015-03-28T11:40:56.936Z [NOTICE] [-] [core] Shutting down

I tried to trace the code in outbound.js, and I think I found the issue in `HMailItem.prototype.found_mx`. After processing all the records, adding the address families, ports etc, the resulting list is overwritten:

        this.mxlist = [];
        for (var mx in mxlist) {
            if (cfg.ipv6_enabled) {
                this.mxlist.push(
                    { exchange: mxlist[mx].exchange, priority: mxlist[mx].priority, port: mxlist[mx].port, using_lmtp: mxlist[mx].using_lmtp, family: 'AAAA' },
                    { exchange: mxlist[mx].exchange, priority: mxlist[mx].priority, port: mxlist[mx].port, using_lmtp: mxlist[mx].using_lmtp, family: 'A' }
                );
            }
            else {
                mxlist[mx].family = 'A';
                this.mxlist.push(mxlist[mx]);
            }
        }

        this.mxlist = mxlist; // <--- Overwrites all the changes made above!

If I remove this line (Commit to fork [here](https://github.com/carlpett/Haraka/commit/7102ce56803acfbe1b5a01c3af8b34acdbca705b)), everything works as expected. 

I'm a bit concerned that I may have misdiagnosed this however, seeing as this is my first exposure to Node, and guessing I'm probably not the first one using outbound delivery?

**Comment by smfreegard** [comment]
Ok - just looked at this; your fix is correct.   I'm guessing you have ipv6_enabled which is why no-one else has noticed this.

**Comment by carlpett** [comment]
Yes, that's correct. Thanks!
