### ISSUE TITLE
smtp_forward not work

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#892]
Hi,

I have try to send mail using queue/smtp_forward.
But  I have face a error msg in logs that "552 Authentication required (7C8907E2-328A-42FC-BDF0-CDAB6BEF9F33.1)". 
Here I have also attached screen-shot for same.
![screenshot from 2015-03-30 15 21 20](https://cloud.githubusercontent.com/assets/11587328/6894127/812bc7a6-d6f0-11e4-878d-1443f1e8a93b.png)

**Comment by smfreegard** [comment]
The '552 Authentication required' isn't coming from the smtp_forward plugin, it's coming from the server that you've configured smtp_forward to forward the mail to....

**Comment by sym786** [comment]
Hi,

When I have send mail by using particular smtp, then mails are delivered properly but when I try to send mail using smtp_forward then it shown error. And I have also cross check auth detail. But I don't know why this error occur. If you provide me any guide then it more appreciated.

**Comment by smfreegard** [comment]
Ok - do you want Haraka to send *all* mail to smtp_forward and have the forward server deliver all mail or do you want smtp_forward to only forward mail for domains in the `config/host_list` and have external domains queued to their MX?

**Comment by bhupeshchugh** [comment]
ya, I need to send all mails to smtp_forward and the forward server will send mails to destination.
And one thing also i am using haraka as a MTA in the forward server also.

**Comment by smfreegard** [comment]
Please gist your smtp_forward.ini file please.   And give a rough diagram of your set-up.

**Comment by bhupeshchugh** [comment]
; host to connect to
host=103.255.101.67
;
; port to connect to
port=587
;
; timeout backend connection from pool
;timeout=300
;
; max connections in pool
;max_connections=1000
;
; uncomment to enable TLS to the backend SMTP server
enable_tls=1
;
; for messages that have multiple RCPT, send a separate message for each RCPT
; when forwarding.
;one_message_per_rcpt=true
;
; uncomment to use smtp client authorization
[auth]
auth_type=PLAIN
auth_user=matt
auth_pass=test

This is the configuration of smtp_frorward.ini file.
this IP <host=103.255.101.67> is the address of forward_server.
But unfortunately this will send the mail from the same server. This configuration was not forward the mails to forward server.

**Comment by smfreegard** [comment]
Ok - remove the `[auth]` heading and it should work.   The documentation config file is incorrect.

**Comment by bhupeshchugh** [comment]
Still does not work !!!
Kindly suggest me how to forward the mails?

**Comment by smfreegard** [comment]
Ok - turn your logging up to LOGPROTOCOL (`echo LOGPROTOCOL > config/loglevel`) and try again, then provide the full log output from that session.

**Comment by bhupeshchugh** [comment]
Here below the sceenshot of server logs.
 ![smtp_log1](https://cloud.githubusercontent.com/assets/11794501/7065135/4848cb70-ded2-11e4-88b2-ed3c54e9851c.png)
![smtp_log2](https://cloud.githubusercontent.com/assets/11794501/7065140/4e94e086-ded2-11e4-91da-f9ce071ff0a5.png)
![smtp_log3](https://cloud.githubusercontent.com/assets/11794501/7065143/54b10a76-ded2-11e4-8c98-7d9244a5b741.png)

**Comment by smfreegard** [comment]
Are you trying to deliberately waste my time?   Screenshots aren't particularly helpful as it's painful to read but especially so when they don't actually show the problem!

I suggest you use SSH next time and copy and paste the logs.   

The big long string in the log output e.g.: `C06870C3-6746-4AF6-BA77-A26B9F9AA128.1` is the transaction ID, the bit before the `.1` e.g. `C06870C3-6746-4AF6-BA77-A26B9F9AA128` is the session ID.    Replicate the problem you are having and then find the session ID in the logs, then grep the whole session transaction out of the log with `grep C06870C3-6746-4AF6-BA77-A26B9F9AA128 /path/to/log.file` and paste it here.

**Comment by bhupeshchugh** [comment]
As per your suggestion, i have sent you logs according to your requirement.

[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running lookup_rdns hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running connect hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running ehlo hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running capabilities hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running capabilities hook in auth/flat_file plugin
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] hook=capabilities plugin=auth/flat_file function=hook_capabilities params="" retval=CONT msg=""
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running capabilities hook in tls plugin
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] hook=capabilities plugin=tls function=tls_capabilities params="" retval=CONT msg=""
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 250-PIPELINING
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 250-8BITMIME
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 250-SIZE 500000
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 250 AUTH LOGIN PLAIN CRAM-MD5
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hook in auth/flat_file plugin
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 334 VXNlcm5hbWU6
[INFO] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="AUTH" retval=OK msg=""
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hook in auth/flat_file plugin
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 334 UGFzc3dvcmQ6
[INFO] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="bWF0dA==" retval=OK msg=""
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hooks
[DEBUG] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] running unrecognized_command hook in auth/flat_file plugin
[PROTOCOL] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] S: 235 Authentication successful
[INFO] [CF44E856-B94E-49E4-BFD4-A2FE2EDBDCCD] [core] hook=unrecognized_command plugin=auth/flat_file function=hook_unrecognized_command params="dGVzdA==" retval=OK msg=""

**Comment by smfreegard** [comment]
This shows a successful authentication.   Where's the rest of it?

This whole issue is about an authentication error is it not?  That is what @sym786 raised this issue for...
