### ISSUE TITLE
How to add text or image in every email

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#894]
Hi,

I want to attached text or image in every email, Is it possible. If yes then please guide me.

**Comment by baudehlo** [comment]
Yes, see transaction.add_body_filter()

http://haraka.github.io/manual/Transaction.html

**Comment by sym786** [comment]
where can i use this code. i means in which file i should put this code. would you describe more about this.

**Comment by baudehlo** [comment]
You need to create a plugin which uses the API. There are tutorials for
writing plugins on the site.
