### ISSUE TITLE
Allow specifying plugin timeout for plugins having a slash in their name.

### ISSUE THREAD

**Issue by celesteking** [baudehlo/Haraka#898]
For ex., you've got plugin named `queue/something.js`.

https://github.com/celesteking/Haraka/commit/67e477dd1cd0474440612005cea13e8832022749 will allow you to specify timeout in `queue:something.timeout` .

**Comment by smfreegard** [comment]
Doesn't putting the timeout file in `queue/somthing.timeout` work?

**Comment by celesteking** [comment]
Yes, indeed, that worked. This should really be mentioned in docs somewhere.

**Comment by smfreegard** [comment]
Ok - done: https://github.com/baudehlo/Haraka/blob/master/docs/CoreConfig.md

**Comment by celesteking** [comment]
thanks sweeties
