### ISSUE TITLE
Allow specifying plugin name instead of plugin object in results_store.add() call

### ISSUE THREAD

**Issue by celesteking** [baudehlo/Haraka#909]
connection.results.add() should accept a String instead of current Object. 
```{name: 'blah'}``` works, but garbles the output.

**Comment by msimerson** [comment]
It [can't](https://github.com/baudehlo/Haraka/blob/master/result_store.js#L83). If you change the [API of logger](https://github.com/baudehlo/Haraka/blob/master/logger.js#L166) so I can pass in an initial string instead of a plugin name, I'd happily update result_store.

**Comment by celesteking** [comment]
```log_if_level``` is essentially using implicit ```plugin.toString()``` call, so that shouldn't be a problem.

**Comment by msimerson** [comment]
Are you [sure](https://github.com/baudehlo/Haraka/blob/master/logger.js#L189) about that? I'd be happy to be wrong.
