### ISSUE TITLE
possible info leak?

### ISSUE THREAD

**Issue by celesteking** [baudehlo/Haraka#917]
I'm against [this](https://github.com/baudehlo/Haraka/blob/master/plugins/auth/auth_base.js#L96) line:
```  connection.notes.auth_passwd = credentials[1];```

**Comment by smfreegard** [comment]
And your reasoning is?  It's used for this https://github.com/baudehlo/Haraka/blob/master/plugins/prevent_credential_leaks.js

Feel free to remove it from your own fork.

**Comment by celesteking** [comment]
The reasoning is possibility of password sniffing via rogue plugin that interprets user data. But I'm just theorizing.
