### ISSUE TITLE
Haraka service automatically got Shutting down

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#927]
I have an issue when I have try to send mail then haraka service automatically shutting down.
Here below I have mention logs -
------------------
[PROTOCOL] [9FB0C640-B5FE-4B27-B670-3D41BBA51457.1] [dkim_sign] selector: wedapr15
[INFO] [9FB0C640-B5FE-4B27-B670-3D41BBA51457.1] [dkim_sign] signed for falakstar.org
[DEBUG] [9FB0C640-B5FE-4B27-B670-3D41BBA51457.1] [core] hook=queue_outbound plugin=dkim_sign function=hook_queue_outbound params="" retval=CONT msg=""
[NOTICE] [9FB0C640-B5FE-4B27-B670-3D41BBA51457.1] [core] queue code=CONT msg=""
[INFO] [-] [core] [outbound] Sending email as a transaction
[INFO] [-] [core] [outbound] Adding missing Message-Id header
[CRIT] [-] [core] TypeError: Object NaN has no method 'replace'
[CRIT] [-] [core]     at Header.add (/usr/local/lib/node_modules/Haraka/mailheader.js:170:19)
[CRIT] [-] [core]     at Transaction.add_leading_header (/usr/local/lib/node_modules/Haraka/transaction.js:148:17)
[CRIT] [-] [core]     at Object.exports.send_trans_email (/usr/local/lib/node_modules/Haraka/outbound.js:427:17)
[CRIT] [-] [core]     at Object.exports.send_email (/usr/local/lib/node_modules/Haraka/outbound.js:344:21)
[CRIT] [-] [core]     at Connection.queue_outbound_respond (/usr/local/lib/node_modules/Haraka/connection.js:1552:26)
[CRIT] [-] [core]     at callback (/usr/local/lib/node_modules/Haraka/plugins.js:337:39)
[CRIT] [-] [core]     at DKIMSignStream.end_callback (/usr/local/lib/node_modules/Haraka/plugins/dkim_sign.js:207:20)
[CRIT] [-] [core]     at DKIMSignStream.end (/usr/local/lib/node_modules/Haraka/plugins/dkim_sign.js:121:33)
[CRIT] [-] [core]     at MessageStream.onend (stream.js:79:10)
[CRIT] [-] [core]     at MessageStream.EventEmitter.emit (events.js:117:20)
[NOTICE] [-] [core] Shutting down
-----------------

Here I have also mention the Swake command logs last lines -
---------------
Subject: test Wed, 15 Apr 2015 17:21:27 +0530
 -> X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
 -> This is a test mailing
*** Remote host closed connection unexpectedly.
---------------

**Comment by sym786** [comment]
I have notice that when I use 'queue/smtp_forward' plugin then it working fine. I don't understand why this is happing. Kindlly guide me.

**Comment by smfreegard** [comment]
Have you modified your copy of Haraka?  The stack trace indicates that Haraka was trying to add a header, but the value was NaN (not a number) which looking at the line numbers and what should be added doesn't seem possible.

**Comment by sym786** [comment]
You are right. I have make some changes in 'outbound.js' for testing purpose.
However now issue is resolved. Thank You.
