### ISSUE TITLE
How configure Haraka as postfix multiple instance ?

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#928]
I have use postfix but now I want to use Haraka but I can't found postfix below feature in Haraka.

http://www.postfix.org/MULTI_INSTANCE_README.html

Multiple instance provides the facility of running more then one postfix instance on a single host machine. Suppose I have three IPs as below -
192.168.0.1     Hostname.domain.com
192.168.0.2     HostnameA.domain.com
192.168.0.3     HostnameB.domain.com

I follow below steps for sending mails.
Application ->  192.168.0.1 -> it send either 192.168.0.2 or 192.168.0.3

**Comment by smfreegard** [comment]
I don't really understand why you'd want to run multiple Haraka instances.

If you just want to send mail out using a different IP, then use the built-in outbound functions and the `bind` parameter of the MX object returned from hook_get_mx to specify which IP address should be used.

**Comment by msimerson** [comment]
If you want to run multiple instances of Haraka, install it once with 3 different config directories and 3 startup files and run 3 instances. By as @smfreegard points, it, there's better ways to do it.

**Comment by jchook** [comment]
> I don't really understand why you'd want to run multiple Haraka instances.

> If you just want to send mail out using a different IP...

What about the `config/me` greeting?

What about providing different storage per domain? Filters?

I can easily think of 10 reasons why postfix master.cf launching a separate stmdp instance makes enormous sense.

How would you do all of that in a single Haraka instance? Spaghetti code?
