### ISSUE TITLE
How Haraka configure as load balancing purpose ?

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#929]
I want below configuration -

Suppose I have 4 ips as mention below.
104.223.1.11
198.55.116.21
194.135.92.31
194.135.92.41

All IPs different hosts and different location and configured as Haraka.
Now I want to send mail using my application and I have set 104.223.1.11 ip on application. And suppose I shoot 10000 mails from application.
Now I want that 104.223.1.11 approximately equally distribute mails to all three IPs.
Please guide me how can done it.

**Comment by smfreegard** [comment]
I guess your options are:

1)  Run HAProxy on 104.223.1.11 and set-up the other machines to accept HAProxy connections from it.   That will give you the best load balancing.
2)  Write a plugin that runs on 104.223.1.11 that hooks get_mx and distributes the traffic to the other servers (if you are using the built-in outbound features).

**Comment by sym786** [comment]
Hi,
Actually I have not depth knowledge of haproxy with smtp because with postfix I never need it. However I have configure it on Centos and here I have  below mention the /etc/haproxy/haproxy.cfg file data on 104.223.1.11- 	
–-------------------------------------------
global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
     stats socket /var/lib/haproxy/stats


defaults
     mode                    tcp
     log                     global
#   option                  httplog
     option                  dontlognull
#   option http-server-close
#   option forwardfor       except 127.0.0.0/8
     option                  redispatch
     retries                 3
     timeout http-request    20
     timeout queue           86400
     timeout connect         86400
     timeout client          86400
     timeout server          86400
     timeout http-keep-alive 30
     timeout check           20
     maxconn                 50000

listen smtp :25
        mode tcp
        option smtpchk
        balance roundrobin
        option tcplog
        maxconn 10000
        server haraka2 198.55.116.21:587 maxconn  check-send-proxy check inter 10s send-proxy
         server haraka3 194.135.92.31:587 maxconn  check-send-proxy check inter 10s send-proxy
         server haraka3 194.135.92.41:587 maxconn  check-send-proxy check inter 10s send-proxy
–--------------------------------------------- 

I have configure haraka on all Ips I.E. 11,21,31,41 and I want to make 11 is master(HAproxy server) and remaing ips are client. So it request you please guide me how configure it.

**Comment by smfreegard** [comment]
So what's the problem?  Did you set-up config/haproxy_hosts as per the docs?

**Comment by sym786** [comment]
Hi,

I have set all thing. Now master (104.223.1.11) send request to clients (198.55.116.21,194.135.92.31). But in client not accept mail. Here below I have mention the logs of client (198.55.116.21). Kindly advise me.

------------
[NOTICE] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] connect ip=104.223.1.11 port=37530 local_ip=198.55.116.21 local_port=587
[DEBUG] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] running lookup_rdns hooks
[DEBUG] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] [early_talker] state=4 esmtp=false line="PROXY TCP4 103.255.101.48 198.55.116.21 37530 587"
[DEBUG] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] running connect hooks
[PROTOCOL] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] S: 220 lbsmtp2.ssm01.com ESMTP Haraka 2.6.1 ready
[PROTOCOL] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] C: PROXY TCP4 198.55.116.21 194.135.92.31 37530 587 state=1
[PROTOCOL] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] S: 421 PROXY not allowed from  104.223.1.11
[PROTOCOL] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] C: HELO localhost state=1
[DEBUG] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] running helo hooks
[PROTOCOL] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] S: 250 lbs.falakstar.com Hello lbs.falakstar.com [104.223.1.11], Haraka is at your service.
[DEBUG] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] running disconnect hooks
[NOTICE] [D34DED45-CCC6-4A65-9A21-6B99BEF3B4FA] [core] disconnect ip= 104.223.1.11 rdns="lbs.falakstar.com" helo="localhost" relay=N early=Y esmtp=N tls=Y pipe=N txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="421 PROXY not allowed from 103.255.101.48" time=0.007
----------
Thank You.

**Comment by smfreegard** [comment]
https://github.com/baudehlo/Haraka/blob/master/docs/HAProxy.md  - see the part about `haproxy_hosts`
