### ISSUE TITLE
How set same DKIM for different IPs ?

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#933]
Hi,

I have configure haraka with DKIM on three different IPs. As below -
198.55.116.21, 198.55.116.31, 198.55.116.41. But for dkim passed I need to make records of all ips in my domain management panel. But I want that I'm make record only of 21 ip in panel and reflect of all.
For same I have copy-paste dkim(public,private,selector key) of 21 to other two ips. But it not working. While same for postfix working fine.

**Comment by msimerson** [comment]
DKIM does not have anything to do with IPs.
