### ISSUE TITLE
more paramaters for queued_ok

### ISSUE THREAD

**Issue by pixelpaulaus** [baudehlo/Haraka#935]
i believe more paramaters being passed for the hook queued_ok would be usefull such as the filename and the uuid + index
from this line: todo.uuid = todo.uuid + '.' + todo_index;
as when the message is delivered the uuid is that above uuid+index
but when it is queued it does not have the index.
so if i wanted to match the delivered to the queued it can be tricky when dealing with multiple domains for delivery.

**Comment by smfreegard** [comment]
As discussed on IRC - this can't be done because there isn't a 1:1 match between an SMTP transaction and the outbound deliveries when multiple recipients or domains are involved.
