### ISSUE TITLE
Email Bounce issue

### ISSUE THREAD

**Issue by sym786** [baudehlo/Haraka#936]
I have mailed fake ids from my application. But I found that application not able to process bounce.
Here below I have mention the log of mail of /log/haraka.log -
-----------
[PROTOCOL] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6] [core] C: RCPT TO: <chnacllckelcialecteq@gmail.com> state=1
[NOTICE] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6] [core] recipient <chnacllckelcialecteq@gmail.com> code=CONT msg="" sender="bounce@app.ssm01.com"
[PROTOCOL] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6] [core] S: 250 recipient <chnacllckelcialecteq@gmail.com> OK
[PROTOCOL] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6.1] [outbound] C: RCPT TO:<chnacllckelcialecteq@gmail.com>
[NOTICE] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6.1] [outbound] recipient <chnacllckelcialecteq@gmail.com> rejected: 550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at http://support.google.com/mail/bin/answer.py?answer=6596 de9si27369759pdb.176 - gsmtp
[INFO] [DAA706AE-4EA6-4651-816F-C14B4C0BED7E.6.1] [outbound] bouncing mail: Some recipients failed: <chnacllckelcialecteq@gmail.com>
----------
And when I have proceed bounce from application it show below error
--------
Email chnacllckelcialecteq@gmail.com parsed as bounced.
Email chnacllckelcialecteq@gmail.com NOT parsed as bounce! Error: Bounce code not found.
-----
For same I have also attached screen-shot.

The same application working fine with postfix. So please guide me how to resolve it.

![screenshot from 2015-04-20 15 00 03](https://cloud.githubusercontent.com/assets/11587328/7227405/f2cbf86c-e76d-11e4-8684-bb52095b64d7.png)

**Comment by smfreegard** [comment]
How are we to know how your application processed bounces and why it doesn't work here?

You need to troubleshoot this yourself.  It's probably likely that your application requires the bounce in a specific format; therefore you'll have to edit the bounce template and do some experimentation and then come back when you have further information.

**Comment by sym786** [comment]
You are right we have set bounce code in application. But I found that the haraka not send any bounce code. Here I have attached screen-shot of both MTA i.e. Haraka and Postfix.
![postfix bounce](https://cloud.githubusercontent.com/assets/11587328/7228119/a6b33e26-e773-11e4-9abb-3739030724e9.png)
![haraka_bounce](https://cloud.githubusercontent.com/assets/11587328/7228121/ac9aafc2-e773-11e4-909b-c773e33ff9bb.png)


So if you guide me what code send by haraka so I can add same code in application.

**Comment by smfreegard** [comment]
That's because Haraka isn't RFC 3464 compliant (yet) and Postfix is: https://tools.ietf.org/html/rfc3464

You can edit config/outbound.bounce_message and add {extended_reason} to the template, which will return the code and response from the upstream for each recipient though, but that probably won't be enough to satisfy your application I expect.

You'll probably need to modify Haraka to send RFC 3464 compliant multipart messages; in which case - the patches would be most welcome.

**Comment by msimerson** [comment]
Opened as a feature request in #937
