### ISSUE TITLE
add connect_pre hook to reduce plugin ordering issues

### ISSUE THREAD

**Issue by msimerson** [baudehlo/Haraka#947]
* lookup\_rdns - called to look up the rDNS - return the rDNS via `next(OK, rdns)`

There are 0 plugins that use this hook in this way.

There are a handful of plugins that use this hook in different ways: graph, karma, limit, process_title, profile, rate_limit, log. The most common use of this hook is to increment counters and initialize data structures. As such, any plugin that uses lookup_rdns in the documented way is likely to negatively impact that usage, unless careful attention to ordering in config/plugins is attended to.

Proposal:
* add a `connect_pre` hook, that always runs upon every connection, doing exactly what all the current plugins that use lookup_rdns expect.
* the connect_pre hook ignores plugin return codes

**Comment by msimerson** [comment]
Here's a similar / related issue:

My `karma` plugin initializes its "to-score" list on the lookup_rdns hook. In general, I want karma to run **after** every other plugin on every hook, as karma is processing the results of those other plugins. On the lookup_rdns hook, `data.uribl` checks the rdns hostname and may attempt to reject the connection. When it does, `karma` will catch the DENY and permit the connection to continue (likely to reject later, after capturing some metadata). The mechanism available to override that DENY is `next(OK)`, which also has the undesired effect of skipping other plugins from processing on the lookup_rdns hook. Since `karma` runs after uribl, its init hook doesn't get called. Having rDNS listed on the URIBL then becomes a handy way to bypass karma.

This is not an issue that can be solved by rearranging the order of plugins on the hook.

### potential solutions
* have a connection setup and teardown hooks that plugins are always run on
* [create a runtime flag that marks a plugin as 'always run'](https://github.com/baudehlo/Haraka/pull/951)
* ...

### workarounds
* modify data.uribl and add reject=false options (like I did for many other plugins)

### hacks
* have karma try to init itself on every hook (bandaid, doesn't solve the problem)

**Comment by smfreegard** [comment]
The most obvious answer and simplest solution (other than adding a bunch of extra hooks) is that you simply modify the hook_deny logic to continue running plugins after next(OK) is returned.

**Comment by smfreegard** [comment]
I guess you could also add a different constant to all hook_deny to maintain the existing functionality too.  e.g. OKCONT for the new behaviour or something like that.

**Comment by msimerson** [comment]
> The most obvious answer ... is ... modify the hook_deny logic to continue running plugins after next(OK) is returned.

Even if I do hook deny, that's only a chance at working because there's no guarantee that my plugin will  get to run hook_deny. Especially not if other plugin authors also hook deny for their purposes. It's also  redundant code that every plugin that wants to maintain accurate counters needs to have.

**Comment by smfreegard** [comment]
> Even if I do hook deny, that's only a chance at working because there's no guarantee that my plugin will get to run hook_deny. Especially not if other plugin authors also hook deny for their purposes.

It's got more chance of running than if we add a regular connect_pre hook as someone else could still hook it, list it above karma or whatever plugin and return next(OK).

Looking at the disconnect hook - it doesn't even read the retval, so there would be no problem making that a special case and ignoring any other result other than CONT and therefore ensuring that all plugins on that hook always run.

I can't say the same for `lookup_rdns` though and I can see a number of reasons why you wouldn't want the same behaviour as it would be perfectly valid to return DENY there.

Therefore a `connect_pre` hook with the same behaviour as `disconnect` and that wouldn't be that confusing if it solves this particular problem for you.

**Comment by smfreegard** [comment]
The only thing that occurs to me with `disconnect` is that it might be interesting to prevent it from actually closing our end of the socket if `next(OK)` was returned, just to see what the client would do.  But aside from an interesting experiment - I guess it's probably not that useful in production.

**Comment by msimerson** [comment]
> Therefore a connect_pre hook with the same behaviour as disconnect and that wouldn't be that confusing if it solves this particular problem for you.

That's exactly what I proposed: "pre_connect hook that ignores plugin return codes" and it "solves" this issue for every plugin that wants to initialize itself at the start of each connection.

**Comment by smfreegard** [comment]
Code it up then and see what baudelho says.
