### ISSUE TITLE
Outbound alias

### ISSUE THREAD

**Issue by DaAwesomeP** [baudehlo/Haraka#963]
I am trying to forward email with aliases. How can I do this with Haraka and not another SMTP server? I noticed that the `smtp_forward` plugin in trying to connect to another server and not use itself as the server. I want Haraka to only accept email at its own domain and then forward those emails to other addresses on the internet based on the alias configuration. I do not want users to actually be able to log in to the server. Is this possible?

**Comment by DaAwesomeP** [comment]
@smfreegard I know that it can be done, but how? I can't quite find the right info in the docs.

**Comment by smfreegard** [comment]
Create a queue plugin that does this:

`````javascript
exports.hook_queue = function (next, connection) {
    var transaction = connection.transaction;
    outbound.send_email(connection.transaction, function(retval, msg) {
        switch(retval) {
            case constants.ok:
                return next(OK, msg);
                break;
            case constants.deny:
                return next(DENY, msg);
                break;
            default:
                return next(DENYSOFT, msg);
        }
    });
}
`````

Then any recipient that you accept in hook_rcpt will use outbound for delivery.
