### ISSUE TITLE
Haraka crash asn check

### ISSUE THREAD

**Issue by Infern1** [baudehlo/Haraka#968]
Since today have this issue

https://gist.github.com/Infern1/8486ad1bbc84fab5d197

#haraka -v                                                                                                                               
Haraka.js â Version: 2.6.2-toaster

#node -v          
                                                                                                                       v0.10.38

**Comment by smfreegard** [comment]
Node version?

**Comment by baudehlo** [comment]
What was the resolution?

**Comment by msimerson** [comment]
If you view on GitHub, you'll see the linked PR #969

**Comment by baudehlo** [comment]
Got it. Just reading emails right now.
