### ISSUE TITLE
Improve PIPELINING (and early_talker)

### ISSUE THREAD

**Issue by smfreegard** [baudehlo/Haraka#970]
- Current PIPELINING support in Haraka doesn't buffer responses to pipelined commands - it works like this:

`````
 C: EHLO dbc.mtview.ca.us
 S: 250-innosoft.com
 S: 250 PIPELINING
 C: MAIL FROM:<mrose@dbc.mtview.ca.us>
 C: RCPT TO:<ned@innosoft.com>
 C: RCPT TO:<dan@innosoft.com>
 C: RCPT TO:<kvc@innosoft.com>
 C: DATA
`````

Haraka will read each of these commands line-by-line and in turn it will respond to each individually.   What it should do is buffer each response and flush them in response to DATA which is more efficient as we reduce the number of packets sent.

- There is no support in outbound for PIPELINING.   Add support to outbound as it's a potentially big performance win.

- Early talker delay should be removed from core entirely (why delay an early_talker?)

- early_talker plugin should introduce a small delay at hook_connect to detect pipelining before the banner is sent.   rDNS lookups might provide sufficient delay for core to detect the earlytalker, but we need 500ms or so to be sure in all cases.

- early_talker: make connect and data delays optional and skip for relays and localhost.

**Comment by msimerson** [comment]
+1

**Comment by celesteking** [comment]
+1 also see #538

**Comment by smfreegard** [comment]
@celesteking try https://github.com/baudehlo/Haraka/pull/983

**Comment by celesteking** [comment]
It works for me, thanks.
